create database ControlEscolar;
Use controlescolar
create table usuario(
idusuario int primary key auto_increment,
nombre varchar(50),
apellidopaterno varchar(50),
apellidomaterno varchar(50),
contrasena varchar(20)
);

create table alumno(
NumControl int primary key AUTO_INCREMENT,
nombre varchar(50),
ApellidoPaterno varchar(50),
ApellidoMaterno varchar(50),
FechaNacimiento varchar (50),
Domicilio varchar(50),
CorreoElectronico varchar (50),
Sexo varchar (50),
estados varchar(50),
ciudades varchar (50)
);

create table Estados(
codigo varchar (100) primary key,
Nombre varchar (100)
);

create table Ciudades(
 codigociudad int primary key AUTO_INCREMENT,
 nombre varchar (100),
 fkcodigo varchar (100),
 foreign key (fkcodigo)references Estados(codigo)
 ); 
 #region estados
 insert into Estados values('AGU','Aguascalientes'),('BCN','Baja California'),('BCS','Baja California Sur'),('CAM','Campeche'),
 ('CHP','Chiapas'),('CHH','Chihuahua'),('CMX','Ciudad de México'),('COA','Coahuila'),('COL','Colima'),('DUR','Durango'),
 ('GUA','Guanajuato'),('GRO','Guerrero'),('HID','Hidalgo'),('JAL','Jalisco'),('MEX','México'),('MIC','Michoacán'),('MOR','Morelos'),
 ('NAY','Nayarit'),('NLE','Nuevo León'),('OAX','Oaxaca'),('PUE','Puebla'),('QUE','Querétaro'),('ROO','Quintana Roo'),
 ('SLP','San Luis Potosí'),('SIN','Sinaloa'),('SON','Sonora'),('TAB','Tabasco'),('TAM','Tamaulipas'),('TLA','Tlaxcala'),
 ('VER','Veracruz'),('YUC','Yucatán'),('ZAC','Zacatecas');
 #end region
 
 #region Aguascalientes 11
 insert into ciudades values(1,'Aguascalientes','AGU'),(2,'Asientos','AGU'),(3,'Calvillo','AGU'),(4,'Cosío','AGU'),(5,'ElLlano','AGU'),
 (6,'JesúsMaría','AGU'),(7,'PabellóndeArteaga','AGU'),(8,'RincóndeRomos','AGU'),(9,'SanFranciscodelosRomo','AGU'),
 (10,'SanJosédeGracia','AGU'),(11,'Tepezalá','AGU');
# end region

#region Baja California 5
insert into ciudades values (null,'Ensenada','BCN'),(null,'Mexicali','BCN'),(null,'Tecate','BCN'),(null,'Tijuana','BCN'),
(null,'Playas de Rosarito','BCN');

#end region

# region baja california sur 5
insert into ciudades values(null,'LaPaz','BCS'),(null,'Los Cabos','BCS'),(null,'Loreto','BCS'),(null,'Mulegé','BCS'),
(null,'Comondú','BCS');
# end region

# region campeche 11
insert into ciudades values(null,'Calakmul','CAM'),(null,'Calkiní','CAM'),(null,'Campeche','CAM'),(null,'Candelaria','CAM'),
(null,'Carmen','CAM'),(null,'Champotón','CAM'),(null,'Escárcega','CAM'),(null,'Hecelchakán','CAM'),(null,'Hopelchén','CAM'),
(null,'Palizada','CAM'),(null,'Tenabo','CAM');
# end region

#region chiapas 118
insert into ciudades values(null,'Acacoyagua','CHP'),(null,'Acala','CHP'),(null,'Acapetahua','CHP'),(null,'Aldama','CHP'),
(null,'Altamirano','CHP'),(null,'Amatán','CHP'),(null,'AmatenangodelaFrontera','CHP'),(null,'AmatenangodelValle','CHP'),(null,'ÁngelAlbinoCorzo','CHP'),
(null,'Arriaga','CHP'),(null,'BejucaldeOcampo','CHP'),(null,'BellaVista','CHP'),(null,'BeneméritodelasAméricas','CHP'),(null,'Berriozábal','CHP'),(null,'Bochil','CHP'),
(null,'Cacahoatán','CHP'),(null,'Chalchihuitán','CHP'),(null,'Chamula','CHP'),(null,'Chanal','CHP'),(null,'Chapultenango','CHP'),(null,'Catazajá','CHP'),(null,'Chenalhó','CHP'),
(null,'ChiapadeCorzo','CHP'),(null,'Chiapilla','CHP'),(null,'Chicoasén','CHP'),(null,'Chicomosuelo','CHP'),(null,'Cintalpa','CHP'),(null,'Chilón','CHP'),(null,'Coapilla','CHP'),
(null,'ComitándeDomínguez','CHP'),(null,'Copainalá','CHP'),(null,'ElBosque','CHP'),(null,'ElPorvenir','CHP'),(null,'Escuintla','CHP'),(null,'FranciscoLeón','CHP'),(null,'FronteraComalapa','CHP'),
(null,'FronteraHidalgo','CHP'),(null,'Huehuetán','CHP'),(null,'Huitiupán','CHP'),(null,'Huixtán','CHP'),(null,'Huixtla','CHP'),(null,'Ixhuatán','CHP'),(null,'Ixtacomitán','CHP'),(null,'Ixtapa','CHP'),
(null,'Ixtapangajoya','CHP'),(null,'Jiquipilas','CHP'),(null,'Jitotol','CHP'),(null,'Juárez','CHP'),(null,'LaConcordia','CHP'),(null,'LaGrandeza','CHP'),(null,'LaIndependencia','CHP'),(null,'LaLibertad','CHP'),
(null,'LaTrinitaria','CHP'),(null,'Larráinzar','CHP'),(null,'LasMargaritas','CHP'),(null,'LasRosas','CHP'),(null,'Mapastepec','CHP'),(null,'MaravillaTenejapa','CHP'),(null,'MarquésdeComillas','CHP'),(null,'MazapadeMadero','CHP'),
(null,'Mazatán','CHP'),(null,'Metapa','CHP'),(null,'Mitontic','CHP'),(null,'MontecristodeGuerrero','CHP'),(null,'Motozintla','CHP'),(null,'NicolásRuíz','CHP'),(null,'Ocosingo','CHP'),(null,'Ocotepec','CHP'),(null,'OcozocoautladeEspinosa','CHP'),
(null,'Ostuacán','CHP'),(null,'Osumacinta','CHP'),(null,'Oxchuc','CHP'),(null,'Palenque','CHP'),(null,'Pantelhó','CHP'),(null,'Pantepec','CHP'),(null,'Pichucalco','CHP'),(null,'Pijijiapan','CHP'),(null,'PuebloNuevoSolistahuacán','CHP'),(null,'Rayón','CHP'),
(null,'Reforma','CHP'),(null,'Sabanilla','CHP'),(null,'SaltodeAgua','CHP'),(null,'SanAndrésDuraznal','CHP'),(null,'SanCristóbaldelasCasas','CHP'),(null,'SanFernando','CHP'),(null,'SanJuanCancuc','CHP'),(null,'SanLucas','CHP'),(null,'SantiagoelPinar','CHP'), 
(null,'Siltepec','CHP'),(null,'Simojovel','CHP'),(null,'Sitalá','CHP'),(null,'Socoltenango','CHP'),(null,'Solosuchiapa','CHP'),(null,'Soyaló','CHP'),(null,'Suchiapa','CHP'),(null,'Suchiate','CHP'),(null,'Sunuapa','CHP'),(null,'Tapachula','CHP'),(null,'Tapalapa','CHP'),
(null,'Tapilula','CHP'),(null,'Tecpatán','CHP'),(null,'Tenejapa','CHP'),(null,'Teopisca','CHP'),(null,'Tila','CHP'),(null,'Tonalá','CHP'),(null,'Totolapa','CHP'),(null,'Tumbalá','CHP'),(null,'TuxtlaChico','CHP'),(null,'TuxtlaGutiérrez','CHP'),(null,'Tuzantán','CHP'),
(null,'Tzimol','CHP'),(null,'UniónJuárez','CHP'),(null,'VenustianoCarranza','CHP'),(null,'VillaComaltitlán','CHP'),(null,'VillaCorzo','CHP'),(null,'Villaflores','CHP'),(null,'Yajalón','CHP'),(null,'Zinacantán','CHP');
#end region

#region chihuahua 67
insert into ciudades values(null,'Chihuahua','CHH'),(null,'Ahumada','CHH'),(null,'Aldama','CHH'),(null,'Allende','CHH'),(null,'AquilesSerdán','CHH'),(null,'Ascensión','CHH'),
(null,'Bachíniva','CHH'),(null,'Balleza','CHH'),(null,'Batopilas','CHH'),(null,'Bocoyna','CHH'),(null,'Buenaventura','CHH'),(null,'Camargo','CHH'),(null,'Carichí','CHH'),
(null,'CasasGrandes','CHH'),(null,'Chínipas','CHH'),(null,'CiudadJuárez','CHH'),(null,'Coronado','CHH'),(null,'Coyame','CHH'),(null,'Cuauhtémoc','CHH'),(null,'Cusihuiriachi','CHH'),
(null,'Delicias','CHH'),(null,'Dr.BelisarioDomínguez','CHH'),(null,'ElTule','CHH'),(null,'Galeana','CHH'),(null,'GómezFarías','CHH'),(null,'GranMorelos','CHH'),(null,'Guachochi','CHH'),
(null,'Guadalupe','CHH'),(null,'GuadalupeyCalvo','CHH'),(null,'Guazapares','CHH'),(null,'Guerrero','CHH'),(null,'HidalgoDelParral','CHH'),(null,'Huejotitán','CHH'),(null,'IgnacioZaragoza','CHH'),
(null,'Janos','CHH'),(null,' Jiménez','CHH'),(null,'Julimes','CHH'),(null,'DeLaCruz','CHH'),(null,'Madera','CHH'),(null,'Maguarichi','CHH'),(null,'Benavides','CHH'),(null,'Matachí','CHH'),
(null,'Matamoros','CHH'),(null,'Meoqui','CHH'),(null,'Morelos','CHH'),(null,'Moris','CHH'),(null,'Namiquipa','CHH'),(null,'Nonoava','CHH'),(null,'NuevoCasasGrandes','CHH'),(null,'Ocampo','CHH'),
(null,'Ojinaga','CHH'),(null,'G.Guerrero','CHH'),(null,'RivaPalacio','CHH'),(null,'Rosales','CHH'),(null,'Rosario','CHH'),(null,'SanFranciscodeBorja','CHH'),(null,'sanFranciscodeConchos','CHH'),
(null,'SanFranciscoDelOro','CHH'),(null,'SantaBárbara','CHH'),(null,'SantaIsabel','CHH'),(null,'Satevó','CHH'),(null,'Saucillo','CHH'),(null,'Temósachi','CHH'),(null,'Urique','CHH'),
(null,' ValledeZaragoza','CHH');

#end region

# region cdmx 16
insert into ciudades values(null,'ÁlvaroObregón','CMX'),(null,'Azcapotzalco','CMX'),(null,'BenitoJuárez','CMX'),(null,'Coyoacán','CMX'),(null,'CuajimalpadeMorelos','CMX'),(null,'Cuauhtémoc','CMX'),
(null,'GustavoA.Madero','CMX'),(null,'Iztacalco','CMX'),(null,'Iztapalapa','CMX'),(null,'MagdalenaContreras','CMX'),(null,'MiguelHidalgo','CMX'),(null,'MilpaAlta','CMX'),(null,'','CMX'),(null,'Tláhuac','CMX'),
(null,'Tlalpan','CMX'),(null,'VenustianoCarranza','CMX'),(null,'Xochimilco','CMX');
#end region

#region coahuila 38
insert into ciudades values(null,'Saltillo','COA'),(null,'Abasolo','COA'),(null,'Acuña','COA'),(null,'Allende','COA'),(null,'Arteaga','COA'),(null,'Candela','COA'),
(null,'Castaños','COA'),(null,'CuatroCiénegas','COA'),(null,'Escobedo','COA'),(null,'FranciscoI.Madero','COA'),(null,'Frontera','COA'),(null,'GeneralCepeda','COA'),(null,'Guerrero','COA'),
(null,'Hidalgo','COA'),(null,'Jiménez','COA'),(null,'Juárez','COA'),(null,'Lamadrid','COA'),(null,'Matamoros','COA'),(null,'Monclova','COA'),(null,'Morelos','COA'),(null,'Múzquiz','COA'),
(null,'Nadadores','COA'),(null,'Nava','COA'),(null,'Ocampo','COA'),(null,'Parras','COA'),(null,'PiedrasNegras','COA'),(null,'Progreso','COA'),(null,'RamosArizpe','COA'),(null,'Sabinas','COA'),
(null,'Sacramento','COA'),(null,'San Buenaventura','COA'),(null,'SanJuandeSabinas','COA'),(null,'SanPedro','COA'),(null,'SierraMojada','COA'),(null,'Torreón','COA'),(null,'Viesca','COA'),
(null,'VillaUnión','COA'),(null,'Zaragoza','COA');
  
#end region

#region colima 10
insert into ciudades values(null,'Armería','COL'),(null,'Colima','COL'),(null,'Comala','COL'),(null,'Coquimatlán','COL'),(null,'Cuauhtémoc','COL'),
(null,'Ixtlahuacán','COL'),(null,'Manzanillo','COL'),(null,'Minatitlán','COL'),(null,'Tecomán','COL'),(null,'Villa de Álvarez','COL');
# end region

#region durango 10
insert into ciudades values(null,'Canatlán','DUR'),(null,'Canelas','DUR'),(null,'ConetodeComonfort','DUR'),(null,'Cuencamé','DUR'),(null,'Durango','DUR'),(null,'ElOro','DUR'),
(null,'GómezPalacio','DUR'),(null,'Gral.SimónBolívar','DUR'),(null,'GuadalupeVictoria','DUR'),(null,'Guanaceví','DUR'),(null,'Hidalgo','DUR'),(null,'Indé','DUR'),(null,'Lerdo','DUR'),
(null,'Mapimí','DUR'),(null,'Mezquital','DUR'),(null,'Nazas','DUR'),(null,'NombredeDios','DUR'),(null,' NuevoIdeal','DUR'),(null,'Ocampo','DUR'),(null,'Otáez','DUR'),(null,'PánucodeCoronado','DUR'),
(null,'PeñónBlanco','DUR'),(null,'Poanas','DUR'),(null,'PuebloNuevo','DUR'),(null,'Rodeo','DUR'),(null,'SanBernardo','DUR'),(null,'SanDimas','DUR'),(null,'SanJuandeGuadalupe','DUR'),
(null,'SanJuandelRío','DUR'),(null,'SanLuisdelCordero','DUR'),(null,'SanPedrodelGallo','DUR'),(null,'SantaClara','DUR'),(null,'SantiagoPapasquiaro','DUR'),(null,'Súchil','DUR'),
(null,'Tamazula','DUR'),(null,'Tepehuanes','DUR'),(null,'Tlahualilo','DUR'),(null,'Topia','DUR'),(null,'Vicente Guerrero','DUR');
#end region   

#region guanajuato 10
insert into ciudades values(null,'aguascalientes','GUA'),(null,'Abasolo','GUA'),(null,'Acámbaro','GUA'),(null,'SanMigueldeAllende','GUA'),(null,'ApaseoelAlto','GUA'),
(null,'ApaseoelGrande','GUA'),(null,'Atarjea','GUA'),(null,'Celaya','GUA'),(null,'ManuelDoblado','GUA'),(null,'Comonfort','GUA'),(null,'Coroneo','GUA'),(null,'Cortazar','GUA'),
(null,'Cuerámaro','GUA'),(null,'DoctorMora','GUA'),(null,'DoloresHidalgo','GUA'),(null,'Huanímaro','GUA'),(null,'Irapuato','GUA'),(null,'JaralmdelProgreso','GUA'),
(null,'Jerécuar','GUA'),(null,'León','GUA'),(null,'Moroleón','GUA'),(null,'Ocampo','GUA'),(null,'PénjamoPueblo','GUA'),(null,'NuevoPurísimadelRincón ','GUA'),(null,'Romita','GUA'),
(null,'Salamanca','GUA'),(null,'Salvatierra','GUA'),(null,'SanDiegodelaUnión','GUA'),(null,'SanFelipe','GUA'),(null,'SanFranciscodelRincón','GUA'),(null,'SanJoséIturbide','GUA'),
(null,'SanLuisdelaPaz','GUA'),(null,'SantaCatarina','GUA'),(null,'SantaCruzdeJuventinoRosas','GUA'),(null,'SantiagoMaravatío','GUA'),(null,'SilaodelaVictoria','GUA'),(null,' Tarandacuao','GUA'),
(null,'Tarimoro','GUA'),(null,'TierraBlanca','GUA'),(null,' Uriangato','GUA'),(null,'ValledeSantiago','GUA'),(null,'Victoria','GUA'),(null,'Villagrán','GUA'),(null,'Xichú','GUA'),
(null,'Yuriria','GUA');
#end region


#region guerrero 74
Insert into ciudades values(null,'AcapulcodeJuárez','GRO'),(null,'Acatepec','GRO'),(null,'Ahuacuotzingo','GRO'),(null,'AjuchitlándelProgreso','GRO'),(null,'AlcozaucadeGuerrero','GRO'),
(null,'Alpoyeca','GRO'),(null,'Apaxtla','GRO'),(null,'Arcelia','GRO'),(null,'AtenangodelRío','GRO'),(null,'AtlamajalcingodelMonte','GRO'),(null,'Atlixtac','GRO'),(null,'AtoyacdeAlvarez','GRO'),
(null,'AyutladelosLibres','GRO'),(null,'Azoyú','GRO'),(null,'BenitoJuárez','GRO'),(null,'BuenavistadeCuéllar','GRO'),(null,'ChilapadeAlvarez','GRO'),(null,'ChilpancingodelosBravo','GRO'),
(null,'CoahuayutladeJoséMaríaIzazaga','GRO'),(null,'CochoapaelGrande','GRO'),(null,'Cocula','GRO'),(null,'Copala','GRO'),(null,'Copalillo','GRO'),(null,'Copanatoyac','GRO'),
(null,'CoyucadeBenítez','GRO'),(null,'CoyucadeCatalán','GRO'),(null,'Cuajinicuilapa','GRO'),(null,'Cualác','GRO'),(null,'Cuautepec','GRO'),(null,'CuetzaladelProgreso','GRO'),(null,'CutzamaladePinzón','GRO'),
(null,'EduardoNeri','GRO'),(null,'FlorencioVillarreal','GRO'),(null,'GeneralCanutoA.Neri','GRO'),(null,'GeneralHeliodoroCastillo','GRO'),(null,'Huamuxtitlán','GRO'),(null,'HuitzucodelosFigueroa','GRO'),
(null,'IgualadelaIndependencia','GRO'),(null,'Igualapa','GRO'),(null,'IxcateopandeCuauhtémoc','GRO'),(null,'JoséAzueta','GRO'),(null,'JoséJoaquindeHerrera','GRO'),(null,'JuanR.Escudero','GRO'),
(null,'LaUnióndeIsidoroMontesdeOca','GRO'),(null,'LeonardoBravo','GRO'),(null,'Malinaltepec','GRO'),(null,'Marquelia','GRO'),(null,'MártirdeCuilapan','GRO'),(null,'Metlatónoc','GRO'),
(null,'Mochitlán','GRO'),(null,'Olinalá','GRO'),(null,'Ometepec','GRO'),(null,'PedroAscencioAlquisiras','GRO'),(null,'Petatlán','GRO'),(null,'Pilcaya','GRO'),(null,'Pungarabato','GRO'),(null,'Quechultenango','GRO'),
(null,'SanLuisAcatlán','GRO'),(null,'SanMarcos','GRO'),(null,'SanMiguelTotolapan','GRO'),(null,'TaxcodeAlarcón','GRO'),(null,'Tecoanapa','GRO'),(null,'TécpandeGaleana','GRO'),(null,'Teloloapan','GRO'),(null,'TepecoacuilcodeTrujano','GRO'),
(null,'Tetipac','GRO'),(null,'TixtladeGuerrero','GRO'),(null,'Tlacoachistlahuaca','GRO'),(null,'Tlacoapa','GRO'),(null,'Tlalchapa','GRO'),(null,'TlalixtaquilladeMaldonado','GRO'),(null,'TlapadeComonfort','GRO'),(null,'Tlapehuala','GRO'),
(null,'Xalpatláhuac','GRO'),(null,'Xochihuehuetlán','GRO'),(null,'Xochistlahuaca','GRO'),(null,'ZapotitlánTablas','GRO'),(null,'Zirándaro','GRO'),(null,'Zitlala','GRO');
#end region 

#region hidalgo 84
insert into ciudades values(null,'Acatlán','HID'),(null,'Acaxochitlán','HID'),(null,'Actopan','HID'),(null,'AguaBlancadeIturbide','HID'),(null,'Ajacuba','HID'),
(null,'Alfajayucan','HID'),(null,'Almoloya','HID'),(null,'Apan','HID'),(null,'Atitalaquia','HID'),(null,'Atlapexco','HID'),(null,'AtotonilcodeTula','HID'),(null,'AtotonilcoelGrande','HID'),
(null,'Calnali','HID'),(null,'Cardonal','HID'),(null,'Chapantongo','HID'),(null,'Chapulhuacán','HID'),(null,'Chilcuautla','HID'),(null,'CuautepecdeHinojosa','HID'),(null,'ElArenal','HID'),
(null,'Eloxochitlán','HID'),(null,'EmilianoZapata','HID'),(null,'Epazoyucan','HID'),(null,'FranciscoI.Madero','HID'),(null,'HuascadeOcampo','HID'),(null,'Huautla','HID'),
(null,'Huazalingo','HID'),(null,'Huehuetla','HID'),(null,'HuejutladeReyes','HID'),(null,'Huichapan','HID'),(null,'Ixmiquilpan','HID'),(null,'JacaladeLedezma','HID'),(null,'Jaltocán','HID'),
(null,'JuárezHidalgo','HID'),(null,'LaMisión','HID'),(null,'Lolotla','HID'),(null,'Metepec','HID'),(null,'Metztitlán','HID'),(null,'MineraldelaReforma','HID'),(null,'MineraldelChico','HID'),
(null,'MineraldelMonte','HID'),(null,'MixquiahualadeJuárez','HID'),(null,'MolangodeEscamilla','HID'),(null,'NicolásFlores','HID'),(null,'NopaladeVillagrán','HID'),(null,'OmitlándeJuárez','HID'),
(null,'PachucadeSoto','HID'),(null,'Pacula','HID'),(null,'Pisaflores','HID'),(null,'ProgresodeObregón','HID'),(null,'SanAgustínMetzquititlán','HID'),(null,'SanAgustínTlaxiaca','HID'),(null,'SanBartoloTutotepec','HID'),
(null,'SanFelipeOrizatlán','HID'),(null,'SanSalvador','HID'),(null,'SantiagodeAnaya','HID'),(null,'SantiagoTulantepecdeLugoGuerre','HID'),(null,'Singuilucan','HID'),(null,'Tasquillo','HID'),
(null,'Tecozautla','HID'),(null,'TenangodeDoria','HID'),(null,'Tepeapulco','HID'),(null,'TepehuacándeGuerrero','HID'),(null,'TepejidelRíodeOcampo','HID'),(null,'Tepetitlán','HID'),
(null,'Tetepango','HID'),(null,'TezontepecdeAldama','HID'),(null,'Tianguistengo','HID'),(null,'Tizayuca','HID'),(null,'Tlahuelilpan','HID'),(null,'Tlahuiltepa','HID'),(null,'Tlanalapa','HID'),
(null,'Tlanchinol','HID'),(null,'Tlaxcoapan','HID'),(null,'Tolcayuca','HID'),(null,'TuladeAllende','HID'),(null,'TulancingodeBravo','HID'),(null,'VilladeTezontepec','HID'),(null,'Xochiatipan','HID'),
(null,'Xochicoatlán','HID'),(null,'Yahualica','HID'),(null,'Zacualtipándeangeles','HID'),(null,'ZapotlándeJuárez','HID'),(null,'Zempoala','HID'),(null,'Zimapán','HID');
#end region	 	

#region jalisco 124
insert into ciudades values (null,'Acatic','JAL'),(null,'AcatlándeJuárez','JAL'),(null,'AhualulcodeMercado','JAL'),(null,'Amacueca','JAL'),(null,'Amatitán','JAL'),
(null,'Ameca','JAL'),(null,'Arandas','JAL'),(null,'AtemajacdeBrizuela','JAL'),(null,'Atengo','JAL'),(null,'Atenguillo','JAL'),(null,'AtotonilcoelAlto','JAL'),(null,'Atoyac','JAL'),
(null,'AutlándeNavarro','JAL'),(null,'Ayotlán','JAL'),(null,'Ayutla','JAL'),(null,'Bolaños','JAL'),(null,'CaboCorrientes','JAL'),(null,'CañadasdeObregón','JAL'),(null,'CasimiroCastillo','JAL'),
(null,'Chapala','JAL'),(null,'Chimaltitán','JAL'),(null,'Chiquilistlán','JAL'),(null,'Cihuatlán','JAL'),(null,'Cocula','JAL'),(null,'Colotlán','JAL'),(null,'ConcepcióndeBuenosAires','JAL'),
(null,'CuautitlándeGarcíaBarragán','JAL'),(null,'Cuautla','JAL'),(null,'Cuquío','JAL'),(null,'Degollado','JAL'),	(null,'Ejutla','JAL'),(null,'ELArenal','JAL'),(null,'ElGrullo','JAL'),
(null,'ElLimón','JAL'),(null,'ElSalto','JAL'),(null,'EncarnacióndeDíaz','JAL'),(null,'Etzatlán','JAL'),(null,'GómezFarías','JAL'),(null,'Guachinango','JAL'),(null,'Guadalajara','JAL'),
(null,'Hostotipaquillo','JAL'),(null,'Huejúcar','JAL'),(null,'HuejuquillaelAlto','JAL'),(null,'IxtlahuacándelosMembrillos','JAL'),(null,'IxtlahuacándelRío','JAL'),(null,'Jalostotitlán','JAL'),(null,'Jamay','JAL'),
(null,'JesúsMaría','JAL'),(null,'JilotlándelosDolores','JAL'),(null,'Jocotepec','JAL'),(null,'Juanacatlán','JAL'),(null,'Juchitlán','JAL'),(null,'LaBarca','JAL'),(null,'LaHuerta','JAL'),
(null,'LaManzanilladelaPaz','JAL'),(null,'LagosdeMoreno','JAL'),(null,'Magdalena','JAL'),(null,'Mascota','JAL'),(null,'Mazamitla','JAL'),(null,'Mexticacán','JAL'),(null,'Mezquitic','JAL'),(null,'Mixtlán','JAL'),
(null,'Ocotlán','JAL'),(null,'OjuelosdeJalisco','JAL'),(null,'Pihuamo','JAL'),(null,'Poncitlán','JAL'),(null,'PuertoVallarta','JAL'),(null,'Quitupan','JAL'),(null,'SanCristóbaldelaBarranca','JAL'),
(null,'SanDiego deAlejandría','JAL'),(null,'SanGabriel','JAL'),(null,'SanJuandelosLagos','JAL'),(null,'SanJuanitodeEscobedo','JAL'),(null,'SanJulián','JAL'),(null,'SanMarcos','JAL'),(null,'SanMartínde Bolaños','JAL'),
(null,'SanMartínHidalgo','JAL'),(null,'SanMiguelelAlto','JAL'),(null,'SanSebastiándelOeste','JAL'),(null,'SantaMaríadelosAngeles','JAL'),(null,'SantaMaríadelOro','JAL'),(null,'Sayula','JAL'),(null,'Tala','JAL'),
(null,'TalpadeAllende','JAL'),(null,'TamazuladeGordiano','JAL'),(null,'Tapalpa','JAL'),(null,'TechalutadeMontenegro','JAL'),(null,'Tecolotlán','JAL'),(null,'Tenamaxtlán','JAL'),(null,'Teocaltiche','JAL'),
(null,'TeocuitatlándeCorona','JAL'),(null,'TepatitlándeMorelos','JAL'),(null,	'Tequila','JAL'),(null,'Teuchitlán','JAL'),(null,'TizapánelAlto','JAL'),(null,'TlajomulcodeZúñiga','JAL'),(null,'Tlaquepaque','JAL'),
(null,'Tolimán','JAL'),(null,'Tomatlán','JAL'),(null,'Tonalá','JAL'),(null,'Tonaya','JAL'),(null,'Tonila','JAL'),(null,'Totatiche','JAL'),(null,'Tototlán','JAL'),(null,'Tuxcacuesco','JAL'),
(null,'Tuxcueca','JAL'),(null,'Tuxpan','JAL'),(null,'UnióndeSanAntonio','JAL'),(null,'Unión deTula','JAL'),(null,'Valle deGuadalupe','JAL'),(null,'Valle deJuárez','JAL'),(null,'Villa Corona','JAL'),
(null,'Villa Guerrero','JAL'),(null,'Villa Hidalgo','JAL'),(null,'Villa Purificación','JAL'),(null,'YahualicadeGonzálezGallo','JAL'),(null,'Zapopan','JAL'),(null,'Zapotiltic','JAL'),
(null,'ZapotitlándeVadillo','JAL'),(null,'ZapotlándelRey','JAL'),(null,'ZapotlánelGrande','JAL'),(null,'Zapotlanejo','JAL');
#end region

# region mexico 120
insert into ciudades values(null,'Acambay','MEX'),(null,'Acolman','MEX'),(null,'Aculco','MEX'),(null,'AlmoloyadeAlquisiras','MEX'),(null,'AlmoloyadeJuárez','MEX'),(null,'AlmoloyadelRío','MEX'),
(null,'Amanalco','MEX'),(null,'Amatepec','MEX'),(null,'Amecameca','MEX'),(null,'Apaxco','MEX'),(null,'Atenco','MEX'),(null,'Atizapán','MEX'),(null,'AtizapándeZaragoza','MEX'),
(null,'Atlacomulco','MEX'),(null,'Atlautla','MEX'),(null,'Axapusco','MEX'),(null,'Ayapango','MEX'),(null,'Calimaya','MEX'),(null,'Capulhuac','MEX'),(null,'Chalco','MEX'),
(null,'ChapadeMota','MEX'),(null,'Chapultepec','MEX'),(null,'Chiautla','MEX'),(null,'Chicoloapan','MEX'),(null,'Chiconcuac','MEX'),(null,'Chimalhuacán','MEX'),(null,'CoacalcodeBerriozábal','MEX'),(null,'CoatepecHarinas','MEX'),
(null,'Cocotitlán','MEX'),(null,'Coyotepec','MEX'),(null,'Cuautitlán','MEX'),(null,'CuautitlánIzcalli','MEX'),(null,'DonatoGuerra','MEX'),(null,'EcatepecdeMorelos','MEX'),(null,'Ecatzingo','MEX'),(null,'ElOro','MEX'),	
(null,'Huehuetoca','MEX'),(null,'Hueypoxtla','MEX'),(null,'Huixquilucan','MEX'),(null,'IsidroFabela','MEX'),(null,'Ixtapaluca','MEX'),(null,'IxtapandelaSal','MEX'),(null,'IxtapandelOro','MEX'),(null,'Ixtlahuaca','MEX'),	
(null,'Jaltenco','MEX'),(null,'Jilotepec','MEX'),(null,'Jilotzingo','MEX'),(null,'Jiquipilco','MEX'),(null,'Jocotitlán','MEX'),(null,'Joquicingo','MEX'),(null,'Juchitepec','MEX'),(null,'La Paz','MEX'),
(null,'Lerma','MEX'),(null,'Luvianos','MEX'),(null,'Malinalco','MEX'),(null,'MelchorOcampo','MEX'),(null,'Metepec','MEX'),(null,'Mexicaltzingo','MEX'),(null,'Morelos','MEX'),(null,'NaucalpandeJuárez','MEX'),
(null,'Nextlalpan','MEX'),(null,'Nezahualcóyotl','MEX'),(null,'NicolásRomero','MEX'),(null,'Nopaltepec','MEX'),(null,'Ocoyoacac','MEX'),(null,'Ocuilan','MEX'),(null,'Otumba','MEX'),(null,'Otzoloapan','MEX'),
(null,'Otzolotepec','MEX'),(null,'Ozumba','MEX'),(null,'Papalotla','MEX'),(null,'Polotitlán','MEX'),(null,'Rayón','MEX'),(null,'SanAntoniolaIsla','MEX'),(null,'SanFelipedelProgreso','MEX'),(null,'SanJosédelRincón','MEX'),
(null,'SanMartíndelasPirámides','MEX'),(null,'SanMateoAtenco','MEX'),(null,'SanSimóndeGuerrero','MEX'),(null,'SantoTomás','MEX'),(null,'SoyaniquilpandeJuárez','MEX'),(null,'Sultepec','MEX'),(null,'Tecámac','MEX'),(null,'Tejupilco','MEX'),
(null,'Temamatla','MEX'),(null,'Temascalapa','MEX'),(null,'Temascalcingo','MEX'),(null,'Temascaltepec','MEX'),(null,'Temoaya','MEX'),(null,'Tenancingo','MEX'),(null,'TenangodelAire','MEX'),
(null,'TenangodelValle','MEX'),(null,'Teoloyucán','MEX'),(null,'Teotihuacán','MEX'),(null,'Tepetlaoxtoc','MEX'),(null,'Tepetlixpa','MEX'),(null,'Tepotzotlán','MEX'),(null,'Tequixquiac','MEX'),
(null,'Texcaltitlán','MEX'),(null,'Texcalyacac','MEX'),(null,'Texcoco','MEX'),(null,'Tezoyuca','MEX'),(null,'Tianguistenco','MEX'),(null,'Timilpan','MEX'),(null,'Tlalmanalco','MEX'),
(null,'TlalnepantladeBaz','MEX'),(null,'Tlatlaya','MEX'),(null,'Toluca','MEX'),(null,'Tonanitla','MEX'),(null,'Tonatico','MEX'),(null,'Tultepec','MEX'),(null,'Tultitlán','MEX'),
(null,'ValledeBravo','MEX'),(null,'ValledeChalcoSolidaridad','MEX'),(null,'VilladelCarbón','MEX'),(null,'VillaGuerrero','MEX'),(null,'VillaVictoria','MEX'),(null,'Xalatlaco','MEX'),
(null,'Xonacatlán','MEX'),(null,'Zacazonapan','MEX'),(null,'Zacualpan','MEX'),(null,'Zinacantepec','MEX'),(null,'Zumpahuacán','MEX'),(null,'VilladeAllende','MEX'),(null,'Zumpango','MEX');
	
#end region 


#region michoacan 
insert into ciudades values(null,'Acuitzio','MIC'),(null,'Aguililla','MIC'),(null,'Alvaro Obregón','MIC'),(null,'Angamacutiro','MIC'),(null,'Angangueo','MIC'),(null,'Apatzingán','MIC'),
(null,'Aporo','MIC'),(null,'Aquila','MIC'),(null,'Ario','MIC'),(null,'Arteaga','MIC'),(null,'Briseñas','MIC'),(null,'Buenavista','MIC'),(null,'Carácuaro','MIC'),
(null,'Charapan','MIC'),(null,'Charo','MIC'),(null,'Chavinda','MIC'),(null,'Cherán','MIC'),(null,'Chilchota','MIC'),(null,'Chinicuila','MIC'),(null,'Chucándiro','MIC'),
(null,'Churintzio','MIC'),(null,'Churumuco','MIC'),(null,'Coahuayana','MIC'),(null,'Coalcomán de Vázquez Pallares','MIC'),(null,'Coeneo','MIC'),(null,'CojumatlándeRégules','MIC'),
(null,'Contepec','MIC'),(null,'Copándaro','MIC'),(null,'Cotija','MIC'),(null,'Cuitzeo','MIC'),(null,'Ecuandureo','MIC'),(null,'EpitacioHuerta','MIC'),
(null,'Erongarícuaro','MIC'),(null,'GabrielZamora','MIC'),(null,'Hidalgo','MIC'),(null,'Huandacareo','MIC'),(null,'Huaniqueo','MIC'),(null,'Huetamo','MIC'),
(null,'Huiramba','MIC'),(null,'Indaparapeo','MIC'),(null,'Irimbo','MIC'),(null,'Ixtlán','MIC'),(null,'Jacona','MIC'),(null,'Jiménez','MIC'),(null,'','MIC'),
(null,'Jiquilpan','MIC'),(null,'José Sixto Verduzco','MIC'),(null,'Juárez','MIC'),(null,'Jungapeo','MIC'),(null,'La Huacana','MIC'),(null,'La Piedad','MIC'),(null,'Lagunillas','MIC'),
(null,'Lázaro Cárdenas','MIC'),(null,'Los Reyes','MIC'),(null,'Nahuatzen','MIC'),(null,'Madero','MIC'),(null,'Marcos Castellanos','MIC'),(null,'Maravatío','MIC'),(null,'Morelia','MIC'),
(null,'Morelos','MIC'),(null,'Nuevo Parangaricutiro','MIC'),(null,'Nuevo Urecho','MIC'),(null,'Numarán','MIC'),(null,'Ocampo','MIC'),(null,'Pajacuarán','MIC'),(null,'Panindícuaro','MIC'),
(null,'MúgicaNocupétaro','MIC'),(null,'Paracho','MIC'),(null,'Parácuaro','MIC'),(null,'Penjamillo','MIC'),(null,'Peribán','MIC'),(null,'Purépero','MIC'),(null,'Puruándiro','MIC'),
(null,'Queréndaro','MIC'),(null,'Quiroga','MIC'),(null,'Sahuayo','MIC'),(null,'Salvador Escalante','MIC'),(null,'San Lucas','MIC'),(null,'Santa Ana Maya','MIC'),
(null,'Senguio','MIC'),(null,'Susupuato','MIC'),(null,'Tacámbaro','MIC'),(null,'Tancítaro','MIC'),(null,'Tangamandapio','MIC'),(null,'Tangancícuaro','MIC'),(null,'Tanhuato','MIC'),
(null,'Taretan','MIC'),(null,'Tarímbaro','MIC'),(null,'Tepalcatepec','MIC'),(null,'Tingindín','MIC'),(null,'Tingambato','MIC'),(null,'Tiquicheo de Nicolás Romero','MIC'),(null,'Tlalpujahua','MIC'),
(null,'Tlazazalca','MIC'),(null,'Tocumbo','MIC'),(null,'Tumbiscatío','MIC'),(null,'Turicato','MIC'),(null,'Tuxpan','MIC'),(null,'Tuzantla','MIC'),(null,'Tzintzuntzan','MIC'),
(null,'Tzitzio','MIC'),(null,'Uruapan','MIC'),(null,'Venustiano Carranza','MIC'),(null,'Villamar','MIC'),(null,'Vista Hermosa','MIC'),(null,'Yurécuaro','MIC'),(null,'Zacapu','MIC'),
(null,'Zamora','MIC'),(null,'Zináparo','MIC'),(null,'Zinapécuaro','MIC'),(null,'Ziracuaretiro','MIC'),(null,'Zitácuaro','MIC');
#end region

#region morelos 32
insert into ciudades values(null,'Amacuzac','MOR'),(null,'Atlatlahucan','MOR'),(null,'Axochiapan','MOR'),(null,'Ayala','MOR'),(null,'Coatlán del Río','MOR'),(null,'Cuautla','MOR'),
(null,'Cuernavaca','MOR'),(null,'Emiliano Zapata','MOR'),(null,'Huitzilac','MOR'),(null,'Jantetelco','MOR'),(null,'Jiutepec','MOR'),(null,'Jojutla','MOR'),(null,'Jonacatepec','MOR'),
(null,'Mazatepec','MOR'),(null,'Miacatlán','MOR'),(null,'Ocuituco','MOR'),(null,'Puente de Ixtla','MOR'),(null,'Temixco','MOR'),(null,'Temoac','MOR'),(null,'Tepalcingo','MOR'),
(null,'Tepoztlán','MOR'),(null,'Tetecala','MOR'),(null,'Tetela del Volcán','MOR'),(null,'Tlalnepantla','MOR'),(null,'Tlaltizapán','MOR'),(null,'Tlaquiltenango','MOR'),
(null,'Tlayacapan','MOR'),(null,'Totolapan','MOR'),(null,'Xochitepec','MOR'),(null,'Yautepec','MOR'),(null,'Yecapixtla','MOR'),(null,'Zacatepec de Hidalgo','MOR'),(null,'Zacualpan de Amilpas','MOR');	
#end region 

# region nayarit 20
insert into ciudades values(null,'Acaponeta','NAY'),(null,'Ahuacatlán','NAY'),(null,'Amatlán de Cañas','NAY'),(null,'Bahía de Banderas','NAY'),(null,'Compostela','NAY'),
(null,'Del Nayar','NAY'),(null,'Huajicori','NAY'),(null,'Ixtlán del Río','NAY'),(null,'Jala','NAY'),(null,'La Yesca','NAY'),
(null,'Rosamorada','NAY'),(null,'Ruíz','NAY'),(null,'San Blas','NAY'),(null,'San Pedro Lagunillas','NAY'),(null,'Santa María del Oro','NAY'),
(null,'Santiago Ixcuintla','NAY'),(null,'Tecuala','NAY'),(null,'Tepic','NAY'),(null,'Tuxpan','NAY'),(null,'Xalisco','NAY');
#end region


# region  nuevo leon 51
insert into ciudades values (null,'Abasolo','NLE'),(null,'Agualeguas','NLE'),(null,'Allende','NLE'),(null,'Anáhuac','NLE'),(null,'Apodaca','NLE'),(null,'Aramberri','NLE'),
(null,'Bustamante','NLE'),(null,'Cadereyta Jiménez','NLE'),(null,'Carmen','NLE'),(null,'Cerralvo','NLE'),(null,'China','NLE'),(null,'Ciénega de Flores','NLE'),(null,'Dr. Coss','NLE'),
(null,'Dr. Arroyo','NLE'),(null,'Dr. González','NLE'),(null,'Galeana','NLE'),(null,'García','NLE'),(null,'Gral. Escobedo','NLE'),(null,'Gral. Terán','NLE'),(null,'Gral. Treviño','NLE'),
(null,'Gral. Zaragoza','NLE'),(null,'Gral. Zuazua','NLE'),(null,'Gral. Bravo','NLE'),(null,'Guadalupe','NLE'),(null,'Hidalgo','NLE'),(null,'Higueras','NLE'),(null,'Hualahuises','NLE'),
(null,'Iturbide','NLE'),(null,'Juárez','NLE'),(null,'Lampazos de Naranjo','NLE'),(null,'Linares','NLE'),(null,'Los Aldamas','NLE'),(null,'Los Herreras','NLE'),(null,'Los Ramones','NLE'),
(null,'Marín','NLE'),(null,'Melchor Ocampo','NLE'),(null,'Mier y Noriega','NLE'),(null,'Mina','NLE'),(null,'Montemorelos','NLE'),(null,'Monterrey','NLE'),(null,'Parás','NLE'),
(null,'Pesquería','NLE'),(null,'Rayones','NLE'),(null,'Sabinas Hidalgo','NLE'),(null,'Salinas Victoria','NLE'),(null,'San Nicolás de los Garza','NLE'),(null,'San Pedro Garza García','NLE'),
(null,'Santa Catarina','NLE'),(null,'Santiago','NLE'),(null,'Vallecillo','NLE'),(null,'Villaldama','NLE');	
#end region

# region oaxaca 570
insert into ciudades values(null,' Abejones','OAX'),
(null,'Acatlán de Pérez Figueroa','OAX'),
(null,'Animas Trujano','OAX'),
(null,'Asunción Cacalotepec','OAX'),
(null,'Asunción Cuyotepeji','OAX'),
(null,'Asunción Ixtaltepec','OAX'),
(null,'Asunción Nochixtlán','OAX'),
(null,'Asunción Ocotlán','OAX'),
(null,'Asunción Tlacolulita','OAX'),
(null,'Ayoquezco de Aldama','OAX'),
(null,'Ayotzintepec','OAX'),
(null,'Calihualá','OAX'),
(null,'Candelaria Loxicha','OAX'),
(null,'Capulálpam de Méndez','OAX'),
(null,'Chahuites','OAX'),
(null,'Chalcatongo de Hidalgo','OAX'),
(null,'Chiquihuitlán de Benito Juárez','OAX'),
(null,'Ciénega de Zimatlán','OAX'),
(null,'Ciudad Ixtepec','OAX'),
(null,'Coatecas Altas','OAX'),
(null,'Coicoyán de las Flores','OAX'),
(null,'Concepción Buenavista','OAX'),
(null,'Concepción Pápalo','OAX'),
(null,'Constancia del Rosario','OAX'),
(null,'Cosolapa','OAX'),
(null,'Cosoltepec','OAX'),
(null,'Cuilápam de Guerrero','OAX'),
(null,'Cuyamecalco Villa de Zaragoza','OAX'),
(null,'El Barrio de la Soledad','OAX'),
(null,'El Espinal','OAX'),
(null,'Eloxochitlán de Flores Magón','OAX'),
(null,'	Fresnillo de Trujano','OAX'),
(null,' 	Guadalupe de Ramírez','OAX'),
(null,' 	Guadalupe Etla','OAX'),
(null,' 	Guelatao de Juárez','OAX'),
(null,' 	Guevea de Humboldt','OAX'),
(null,' 	Heroica Ciudad de Ejutla de Crespo','OAX'),
(null,' 	Heroica Ciudad de Huajuapan de Leó','OAX'),
(null,'	Heroica Ciudad de Tlaxiaco','OAX'),
(null,' 	Huautepec','OAX'),
(null,' 	Huautla de Jiménez','OAX'),
(null,'	Ixpantepec Nieves','OAX'),
(null,' 	Ixtlán de Juárez','OAX'),
(null,' 	Juchitán de Zaragoza','OAX'),
(null,'	La Compañía','OAX'),
(null,' 	La Pe','OAX'),
(null,'	La Reforma','OAX'),
(null,' 	La Trinidad Vista Hermosa','OAX'),
(null,' 	Loma Bonita','OAX'),
(null,'	Magdalena Apasco','OAX'),
(null,'	Magdalena Jaltepec','OAX'),
(null,' 	Magdalena Mixtepec','OAX'),
(null,' 	Magdalena Ocotlán','OAX'),
(null,' 	Magdalena Peñasco','OAX'),
(null,' 	Magdalena Teitipac','OAX'),
(null,' 	Magdalena Tequisistlán','OAX'),
(null,' 	Magdalena Tlacotepec','OAX'),
(null,' 	Magdalena Yodocono de Porfirio Día','OAX'),
(null,'	Magdalena Zahuatlán','OAX'),
(null,'	Mariscala de Juárez','OAX'),
(null,' 	Mártires de Tacubaya','OAX'),
(null,' 	Matías Romero Avendaño','OAX'),
(null,'	Mazatlán Villa de Flores','OAX'),
(null,' 	Mesones Hidalgo','OAX'),
(null,'	Miahuatlán de Porfirio Díaz','OAX'),
(null,' 	Mixistlán de la Reforma','OAX'),
(null,' 	Monjas','OAX'),
(null,' 	Natividad','OAX'),
(null,' 	Nazareno Etla','OAX'),
(null,' 	Nejapa de Madero','OAX'),
(null,' 	Nuevo Zoquiapam','OAX'),
(null,' 	Oaxaca de Juárez','OAX'),
(null,' 	Ocotlán de Morelos','OAX'),
(null,'	Pinotepa de Don Luis','OAX'),
(null,' 	Pluma Hidalgo','OAX'),
(null,' 	Putla Villa de Guerrero','OAX'),
(null,'	Reforma de Pineda','OAX'),
(null,' 	Reyes Etla','OAX'),
(null,' 	Rojas de Cuauhtémoc','OAX'),
(null,' 	Salina Cruz','OAX'),
(null,' 	San Agustín Amatengo','OAX'),
(null,' 	San Agustín Atenango','OAX'),
(null,'	San Agustín Chayuco','OAX'),
(null,' 	San Agustín de las Juntas','OAX'),
(null,' 	San Agustín Etla','OAX'),
(null,' 	San Agustín Loxicha','OAX'),
(null,' 	San Agustín Tlacotepec','OAX'),
(null,' 	San Agustín Yatareni','OAX'),
(null,' 	San Andrés Cabecera Nueva','OAX'),
(null,'	San Andrés Dinicuiti','OAX'),
(null,'	San Andrés Huaxpaltepec','OAX'),
(null,'	San Andrés Huayapam','OAX'),
(null,' 	San Andrés Ixtlahuaca','OAX'),
(null,'	San Andrés Lagunas','OAX'),
(null,' 	San Andrés Nuxiño','OAX'),
(null,' 	San Andrés Paxtlán','OAX'),
(null,' 	San Andrés Sinaxtla','OAX'),
(null,' 	San Andrés Solaga','OAX'),
(null,' 	San Andrés Teotilalpam','OAX'),
(null,' 	San Andrés Tepetlapa','OAX'),
(null,' 	San Andrés Yaá','OAX'),
(null,' 	San Andrés Zabache','OAX'),
(null,'	San Andrés Zautla','OAX'),
(null,' 	San Antonino Castillo Velasco','OAX'),
(null,' 	San Antonino el Alto','OAX'),
(null,' 	San Antonino Monte Verde','OAX'),
(null,' 	San Antonio Acutla','OAX'),
(null,'	San Antonio de la Cal','OAX'),
(null,' 	San Antonio Huitepec','OAX'),
(null,' 	San Antonio Nanahuatípa','OAX'),
(null,' 	San Antonio Sinicahua','OAX'),
(null,' 	San Antonio Tepetlapa','OAX'),
(null,' 	San Baltazar Chichicápam','OAX'),
(null,' 	San Baltazar Loxicha','OAX'),
(null,' 	San Baltazar Yatzachi el Bajo','OAX'),
(null,' 	San Bartolo Coyotepec','OAX'),
(null,' 	San Bartolo Soyaltepec','OAX'),
(null,' 	San Bartolo Yautepec','OAX'),
(null,'	San Bartolomé Ayautla','OAX'),
(null,' 	San Bartolomé Loxicha','OAX'),
(null,' 	San Bartolomé Quialana','OAX'),
(null,' 	San Bartolomé Yucuañe','OAX'),
(null,'	San Bartolomé Zoogocho','OAX'),
(null,' 	San Bernardo MixtepecSan Blas Atempa','OAX'),
(null,' 	San Carlos Yautepec','OAX'),
(null,' 	San Cristóbal Amatlán','OAX'),
(null,' 	San Cristóbal Amoltepec','OAX'),
(null,' 	San Cristóbal Lachirioag','OAX'),
(null,' 	San Cristóbal Suchixtlahuaca','OAX'),
(null,' 	San Dionisio del Mar','OAX'),
(null,' 	San Dionisio Ocotepec','OAX'),
(null,' 	San Dionisio Ocotlán','OAX'),
(null,' 	San Esteban Atatlahuca','OAX'),
(null,' 	San Felipe Jalapa de Díaz','OAX'),
(null,' 	San Felipe Tejalapam','OAX'),
(null,' 	San Felipe Usila','OAX'),
(null,'	San Francisco Cahuacuá','OAX'),
(null,' 	San Francisco Cajonos','OAX'),
(null,'	San Francisco Chapulapa','OAX'),
(null,' 	San Francisco Chindúa','OAX'),
(null,' 	San Francisco del Mar','OAX'),
(null,' 	San Francisco Huehuetlán','OAX'),
(null,' 	San Francisco Ixhuatán','OAX'),
(null,' 	San Francisco Jaltepetongo','OAX'),
(null,' 	San Francisco Lachigoló','OAX'),
(null,' 	San Francisco Logueche','OAX'),
(null,' 	San Francisco Nuxaño','OAX'),
(null,' 	San Francisco Ozolotepec','OAX'),
(null,'	San Francisco Sola','OAX'),
(null,' 	San Francisco Telixtlahuaca','OAX'),
(null,' 	San Francisco Teopan','OAX'),
(null,' 	San Francisco Tlapancingo','OAX'),
(null,' 	San Gabriel Mixtepec','OAX'),
(null,'	San Ildefonso Amatlán','OAX'),
(null,'	San Ildefonso Sola','OAX'),
(null,'	San Ildefonso Villa Alta','OAX'),
(null,'	San Jacinto Amilpas','OAX'),
(null,' 	San Jacinto Tlacotepec','OAX'),
(null,' 	San Jerónimo Coatlán','OAX'),
(null,' 	San Jerónimo Silacayoapilla','OAX'),
(null,' 	San Jerónimo Sosola','OAX'),
(null,' 	San Jerónimo Taviche','OAX'),
(null,' 	San Jerónimo Tecoátl','OAX'),
(null,'	San Jerónimo Tlacochahuaya','OAX'),
(null,'	San Jorge Nuchita','OAX'),
(null,'	San José Ayuquila','OAX'),
(null,' 	San José Chiltepec','OAX'),
(null,' 	San José del Peñasco','OAX'),
(null,' 	San José del Progreso','OAX'),
(null,' 	San José Estancia Grande','OAX'),
(null,' 	San José Independencia','OAX'),
(null,' 	San José Lachiguiri','OAX'),
(null,' 	San José Tenango','OAX'),
(null,' 	San Juan ?umí','OAX'),
(null,' 	San Juan Achiutla','OAX'),
(null,'	San Juan Atepec','OAX'),
(null,'	San Juan Bautista Atatlahuca','OAX'),
(null,'	San Juan Bautista Coixtlahuaca','OAX'),
(null,' 	San Juan Bautista Cuicatlán','OAX'),
(null,' 	San Juan Bautista Guelache','OAX'),
(null,' 	San Juan Bautista Jayacatlán','OAX'),
(null,' 	San Juan Bautista Lo de Soto','OAX'),
(null,' 	San Juan Bautista Suchitepec','OAX'),
(null,' 	San Juan Bautista Tlachichilco','OAX'),
(null,' 	San Juan Bautista Tlacoatzintepec','OAX'),
(null,'	San Juan Bautista Tuxtepec','OAX'),
(null,' 	San Juan Bautista Valle Nacional','OAX'),
(null,' 	San Juan Cacahuatepec','OAX'),
(null,'	San Juan Chicomezúchil','OAX'),
(null,' 	San Juan Chilateca','OAX'),
(null,' 	San Juan Cieneguilla','OAX'),
(null,' 	San Juan Coatzóspam','OAX'),
(null,'	San Juan Colorado','OAX'),
(null,'	San Juan Comaltepec','OAX'),
(null,' 	San Juan Cotzocón','OAX'),
(null,' 	San Juan de los Cués','OAX'),
(null,'	San Juan del Estado','OAX'),
(null,' 	San Juan del Río','OAX'),
(null,' 	San Juan Diuxi','OAX'),
(null,'	San Juan Evangelista Analco','OAX'),
(null,'	San Juan Guelavía','OAX'),
(null,' 	San Juan Guichicovi','OAX'),
(null,' 	San Juan Ihualtepec','OAX'),
(null,' 	San Juan Juquila Mixes','OAX'),
(null,'	San Juan Juquila Vijanos','OAX'),
(null,'	San Juan Lachao','OAX'),
(null,' 	San Juan Lachigalla','OAX'),
(null,' 	San Juan Lajarcia','OAX'),
(null,' 	San Juan Lalana','OAX'),
(null,' 	San Juan Mazatlán','OAX'),
(null,' 	San Juan Mixtepec','OAX'),
(null,' 	San Juan Mixtepec','YUC'),
(null,' 	San Juan Ozolotepec','OAX'),
(null,' 	San Juan Petlapa','OAX'),
(null,' 	San Juan Quiahije','OAX'),
(null,' 	San Juan Quiotepec','OAX'),
(null,' 	San Juan Sayultepec','OAX'),
(null,'	San Juan Tabaá','OAX'),
(null,' 	San Juan Tamazola','OAX'),
(null,' 	San Juan Teita','OAX'),
(null,' 	San Juan Teitipac','OAX'),
(null,' 	San Juan Tepeuxila','OAX'),
(null,' 	San Juan Teposcolula','OAX'),
(null,' 	San Juan Yaeé','OAX'),
(null,' 	San Juan Yatzona','OAX'),
(null,' 	San Juan Yucuita','OAX'),
(null,' 	San Lorenzo','OAX'),
(null,' 	San Lorenzo Albarradas','OAX'),
(null,' 	San Lorenzo Cacaotepec','OAX'),
(null,' 	San Lorenzo Cuaunecuiltitla','OAX'),
(null,' 	San Lorenzo Texmelucan','OAX'),
(null,' 	San Lorenzo Victoria','OAX'),
(null,' 	San Lucas Camotlán','OAX'),
(null,' 	San Lucas Ojitlán','OAX'),
(null,' 	San Lucas Quiaviní','OAX'),
(null,' 	San Lucas Zoquiápam','OAX'),
(null,'	San Luis Amatlán','OAX'),
(null,'	San Marcial Ozolotepec','OAX'),
(null,' 	San Marcos Arteaga','OAX'),
(null,' 	San Martín de los Cansecos','OAX'),
(null,' 	San Martín Huamelúlpam','OAX'),
(null,' 	San Martín Itunyoso','OAX'),
(null,'	San Martín Lachilá','OAX'),
(null,' 	San Martín Peras','OAX'),
(null,' 	San Martín Tilcajete','OAX'),
(null,'	San Martín Toxpalan','OAX'),
(null,' 	San Martín Zacatepec','OAX'),
(null,' 	San Mateo Cajonos','OAX'),
(null,' 	San Mateo del Mar','OAX'),
(null,' 	San Mateo Etlatongo','OAX'),
(null,' 	San Mateo Nejápam','OAX'),
(null,' 	San Mateo Peñasco','OAX'),
(null,'	San Mateo Piñas','OAX'),
(null,' 	San Mateo Río Hondo','OAX'),
(null,' 	San Mateo Sindihui','OAX'),
(null,' 	San Mateo Tlapiltepec','OAX'),
(null,' 	San Mateo Yoloxochitlán','OAX'),
(null,' 	San Melchor Betaza','OAX'),
(null,' 	San Miguel Achiutla','OAX'),
(null,' 	San Miguel Ahuehuetitlán','OAX'),
(null,' 	San Miguel Aloápam','OAX'),
(null,' 	San Miguel Amatitlán','OAX'),
(null,' 	San Miguel Amatlán','OAX'),
(null,' 	San Miguel Chicahua','OAX'),
(null,' 	San Miguel Chimalapa','OAX'),
(null,' 	San Miguel Coatlán','OAX'),
(null,' 	San Miguel del Puerto','OAX'),
(null,' 	San Miguel del Río','OAX'),
(null,' 	San Miguel Ejutla','OAX'),
(null,' 	San Miguel el Grande','OAX'),
(null,' 	San Miguel Huautla','OAX'),
(null,'	San Miguel Mixtepec','OAX'),
(null,' 	San Miguel Panixtlahuaca','OAX'),
(null,' 	San Miguel Peras','OAX'),
(null,' 	San Miguel Piedras','OAX'),
(null,' 	San Miguel Quetzaltepec','OAX'),
(null,'	San Miguel Santa Flor','OAX'),
(null,'	San Miguel Soyaltepec','OAX'),
(null,' 	San Miguel Suchixtepec','OAX'),
(null,' 	San Miguel Tecomatlán','OAX'),
(null,' 	San Miguel Tenango','OAX'),
(null,' 	San Miguel Tequixtepec','OAX'),
(null,'	San Miguel Tilquiápam','OAX'),
(null,' 	San Miguel Tlacamama','OAX'),
(null,' 	San Miguel Tlacotepec','OAX'),
(null,'	San Miguel Tulancingo','OAX'),
(null,'	San Miguel Yotao','OAX'),
(null,'	San Nicolás','OAX'),
(null,' 	San Nicolás Hidalgo','OAX'),
(null,' 	San Pablo Coatlán','OAX'),
(null,' 	San Pablo Cuatro Venados','OAX'),
(null,' 	San Pablo Etla','OAX'),
(null,' 	San Pablo Huitzo','OAX'),
(null,' 	San Pablo Huixtepec','OAX'),
(null,' 	San Pablo Macuiltianguis','OAX'),
(null,' 	San Pablo Tijaltepec','OAX'),
(null,'	San Pablo Villa de Mitla','OAX'),
(null,' 	San Pablo Yaganiza','OAX'),
(null,' 	San Pedro Amuzgos','OAX'),
(null,' 	San Pedro Apóstol','OAX'),
(null,' 	San Pedro Atoyac','OAX'),
(null,' 	San Pedro Cajonos','OAX'),
(null,' 	San Pedro Comitancillo','OAX'),
(null,' 	San Pedro Coxcaltepec Cántaros','OAX'),
(null,' 	San Pedro el Alto','OAX'),
(null,' 	San Pedro Huamelula','OAX'),
(null,'	San Pedro Huilotepec','OAX'),
(null,'	San Pedro Ixcatlán','OAX'),
(null,'	San Pedro Ixtlahuaca','OAX'),
(null,' 	San Pedro Jaltepetongo','OAX'),
(null,' 	San Pedro Jicayán','OAX'),
(null,'	San Pedro Jocotipac','OAX'),
(null,' 	San Pedro Juchatengo','OAX'),
(null,'	San Pedro Mártir','OAX'),
(null,'	San Pedro Mártir Quiechapa','OAX'),
(null,' 	San Pedro Mártir Yucuxaco','OAX'),
(null,' 	San Pedro Mixtepec','OAX'),
(null,' 	San Pedro Mixtepec','OAX'),
(null,' 	San Pedro Molinos','OAX'),
(null,' 	San Pedro Nopala','OAX'),
(null,' 	San Pedro Ocopetatillo','OAX'),
(null,'	San Pedro Ocotepec','OAX'),
(null,'	San Pedro Pochutla','OAX'),
(null,'	San Pedro Quiatoni','OAX'),
(null,'	San Pedro Sochiapam','OAX'),
(null,'	San Pedro Tapanatepec','OAX'),
(null,' 	San Pedro Taviche','OAX'),
(null,' 	San Pedro Teozacoalco','OAX'),
(null,' 	San Pedro Teutila','OAX'),
(null,' 	San Pedro Tidaá','OAX'),
(null,'	San Pedro Topiltepec','OAX'),
(null,' 	San Pedro Totolapa','OAX'),
(null,' 	San Pedro y San Pablo Ayutla','OAX'),
(null,' 	San Pedro y San Pablo Teposcolula','OAX'),
(null,'	San Pedro y San Pablo Tequixtepec','OAX'),
(null,' 	San Pedro Yaneri','OAX'),
(null,' 	San Pedro Yólox','OAX'),
(null,' 	San Pedro Yucunama','OAX'),
(null,' 	San Raymundo Jalpan','OAX'),
(null,' 	San Sebastián Abasolo','OAX'),
(null,' 	San Sebastián Coatlán','OAX'),
 (null,'	San Sebastián Ixcapa','OAX'),
(null,'San Sebastián Nicananduta','OAX'),
(null,' 	San Sebastián Río Hondo','OAX'),
(null,' 	San Sebastián Tecomaxtlahuaca','OAX'),
(null,' 	San Sebastián Teitipac','OAX'),
(null,' 	San Sebastián Tutla','OAX'),
(null,' 	San Simón Almolongas','OAX'),
(null,' 	San Simón Zahuatlán','OAX'),
(null,'	San Vicente Coatlán','OAX'),
(null,' 	San Vicente Lachixío','OAX'),
(null,' 	San Vicente Nuñú','OAX'),
(null,'	Santa Ana','OAX'),
(null,' 	Santa Ana Ateixtlahuaca','OAX'),
(null,' 	Santa Ana Cuauhtémoc','OAX'),
(null,' 	Santa Ana del Valle','OAX'),
(null,' 	Santa Ana Tavela','OAX'),
(null,' 	Santa Ana Tlapacoyan','OAX'),
(null,'	Santa Ana Yareni	','OAX'),
(null,'Santa Ana Zegache','OAX'),
(null,' 	Santa Catalina Quierí','OAX'),
(null,' 	Santa Catarina Cuixtla','OAX'),
(null,'	Santa Catarina Ixtepeji','OAX'),
(null,' 	Santa Catarina Juquila','OAX'),
(null,' 	Santa Catarina Lachatao','OAX'),
(null,'	Santa Catarina Loxicha','OAX'),
(null,' 	Santa Catarina Mechoacán','OAX'),
(null,'	Santa Catarina Minas','OAX'),
(null,' 	Santa Catarina Quiané','OAX'),
(null,'	Santa Catarina Quioquitani','OAX'),
(null,' 	Santa Catarina Tayata','OAX'),
(null,' 	Santa Catarina Ticuá','OAX'),
(null,'	Santa Catarina Yosonotú','OAX'),
(null,'	Santa Catarina Zapoquila','OAX'),
(null,'	Santa Cruz Acatepec','OAX'),
(null,' 	Santa Cruz Amilpas','OAX'),
(null,' 	Santa Cruz de Bravo','OAX'),
(null,' 	Santa Cruz Itundujia','OAX'),
(null,' 	Santa Cruz Mixtepec','OAX'),
(null,' 	Santa Cruz Nundaco','OAX'),
(null,' 	Santa Cruz Papalutla','OAX'),
(null,' 	Santa Cruz Tacache de Mina','OAX'),
(null,'	Santa Cruz Tacahua','OAX'),
(null,' 	Santa Cruz Tayata','OAX'),
(null,' 	Santa Cruz Xitla','OAX'),
(null,'	Santa Cruz Xoxocotlán','OAX'),
(null,'	Santa Cruz Zenzontepec','OAX'),
(null,' 	Santa Gertrudis','OAX'),
(null,' 	Santa Inés de Zaragoza','OAX'),
(null,' 	Santa Inés del Monte','OAX'),
(null,' 	Santa Inés Yatzeche','OAX'),
(null,' 	Santa Lucía del Camino','OAX'),
(null,' 	Santa Lucía Miahuatlán','OAX'),
(null,' 	Santa Lucía Monteverde','OAX'),
(null,' 	Santa Lucía Ocotlán','OAX'),
(null,' 	Santa Magdalena Jicotlán','OAX'),
(null,' 	Santa María Alotepec','OAX'),
(null,' 	Santa María Apazco','OAX'),
(null,' 	Santa María Atzompa','OAX'),
(null,' 	Santa María Camotlán','OAX'),
(null,' 	Santa María Chachoápam','OAX'),
(null,' 	Santa María Chilchotla','OAX'),
(null,' 	Santa María Chimalapa','OAX'),
(null,' 	Santa María Colotepec','OAX'),
(null,'	Santa María Cortijo','OAX'),
(null,' 	Santa María Coyotepec','OAX'),
(null,' 	Santa María del Rosario','OAX'),
(null,' 	Santa María del Tule','OAX'),
(null,' 	Santa María Ecatepec','OAX'),
(null,' 	Santa María Guelacé','OAX'),
(null,' 	Santa María Guienagati','OAX'),
(null,' 	Santa María Huatulco','OAX'),
(null,' 	Santa María Huazolotitlán','OAX'),
(null,'	Santa María Ipalapa','OAX'),
(null,'	Santa María Ixcatlán','OAX'),
(null,' 	Santa María Jacatepec','OAX'),
(null,' 	Santa María Jalapa del Marqués','OAX'),
(null,'	Santa María Jaltianguis','OAX'),
(null,' 	Santa María la Asunción','OAX'),
(null,' 	Santa María Lachixío','OAX'),
(null,'	Santa María Mixtequilla','OAX'),
(null,' 	Santa María Nativitas','OAX'),
(null,' 	Santa María Nduayaco','OAX'),
(null,' 	Santa María Ozolotepec','OAX'),
(null,'	Santa María Pápalo','OAX'),
(null,' 	Santa María Peñoles','OAX'),
(null,' 	Santa María Petapa','OAX'),
(null,' 	Santa María Quiegolani','OAX'),
(null,' 	Santa María Sola','OAX'),
(null,' 	Santa María Tataltepec','OAX'),
(null,' 	Santa María Tecomavaca','OAX'),
(null,'	Santa María Temaxcalapa','OAX'),
(null,' 	Santa María Temaxcaltepec','OAX'),
(null,' 	Santa María Teopoxco','OAX'),
(null,' 	Santa María Tepantlali','OAX'),
(null,' 	Santa María Texcatitlán','OAX'),
(null,'	Santa María Tlahuitoltepec','OAX'),
(null,' 	Santa María Tlalixtac','OAX'),
(null,' 	Santa María Tonameca','OAX'),
(null,'	Santa María Totolapilla','OAX'),
(null,' 	Santa María Xadani','OAX'),
(null,' 	Santa María Yalina','OAX'),
(null,' 	Santa María Yavesía','OAX'),
(null,' 	Santa María Yolotepec','OAX'),
(null,' 	Santa María Yosoyúa','OAX'),
(null,' 	Santa María Yucuhiti','OAX'),
(null,' 	Santa María Zacatepec','OAX'),
 (null,'	Santa María Zaniza','OAX'),
(null,'	Santa María Zoquitlán','OAX'),
(null,'	Santiago Amoltepec','OAX'),
(null,' 	Santiago Apoala','OAX'),
(null,'	Santiago Apóstol','OAX'),
(null,' 	Santiago Astata','OAX'),
(null,' 	Santiago Atitlán','OAX'),
(null,' 	Santiago Ayuquililla','OAX'),
(null,' 	Santiago Cacaloxtepec','OAX'),
(null,'	Santiago Camotlán','OAX'),
(null,' 	Santiago Chazumba','OAX'),
(null,' 	Santiago Choapam','OAX'),
(null,' 	Santiago Comaltepec','OAX'),
(null,' 	Santiago del Río','OAX'),
(null,' 	Santiago Huajolotitlán','OAX'),
(null,' 	Santiago Huauclilla','OAX'),
(null,' 	Santiago Ihuitlán Plumas','OAX'),
(null,' 	Santiago Ixcuintepec','OAX'),
(null,' 	Santiago Ixtayutla','OAX'),
(null,' 	Santiago Jamiltepec','OAX'),
(null,' 	Santiago Jocotepec','OAX'),
(null,' 	Santiago Juxtlahuaca','OAX'),
(null,' 	Santiago Lachiguiri','OAX'),
(null,' 	Santiago Lalopa','OAX'),
(null,' 	Santiago Laollaga','OAX'),
(null,' 	Santiago Laxopa','OAX'),
(null,' 	Santiago Llano Grande','OAX'),
(null,' 	Santiago Matatlán','OAX'),
(null,' 	Santiago Miltepec','OAX'),
(null,' 	Santiago Minas','OAX'),
(null,' 	Santiago Nacaltepec','OAX'),
(null,' 	Santiago Nejapilla','OAX'),
(null,' 	Santiago Niltepec','OAX'),
(null,'	Santiago Nundiche','OAX'),
(null,'	Santiago Nuyoó','OAX'),
(null,' 	Santiago Pinotepa Nacional','OAX'),
(null,' 	Santiago Suchilquitongo','OAX'),
(null,'	Santiago Tamazola','OAX'),
(null,' 	Santiago Tapextla','OAX'),
(null,' 	Santiago Tenango','OAX'),
(null,' 	Santiago Tepetlapa','OAX'),
(null,' 	Santiago Tetepec','OAX'),
(null,'	Santiago Texcalcingo','OAX'),
(null,' 	Santiago Textitlán','OAX'),
(null,' 	Santiago Tilantongo','OAX'),
(null,' 	Santiago Tillo','OAX'),
(null,' 	Santiago Tlazoyaltepec','OAX'),
(null,' 	Santiago Xanica','OAX'),
(null,' 	Santiago Xiacuí','OAX'),
(null,' 	Santiago Yaitepec','OAX'),
(null,' 	Santiago Yaveo','OAX'),
(null,' 	Santiago Yolomécatl','OAX'),
(null,' 	Santiago Yosondúa','OAX'),
(null,' 	Santiago Yucuyachi','OAX'),
(null,' 	Santiago Zacatepec','OAX'),
(null,' 	Santiago Zoochila','OAX'),
(null,' 	Santo Domingo Albarradas','OAX'),
(null,' 	Santo Domingo Armenta','OAX'),
(null,' 	Santo Domingo Chihuitán','OAX'),
(null,' 	Santo Domingo de Morelos','OAX'),
(null,' 	Santo Domingo Ingenio','OAX'),
(null,' 	Santo Domingo Ixcatlán','OAX'),
(null,' 	Santo Domingo Nuxaá','OAX'),
(null,' 	Santo Domingo Ozolotepec','OAX'),
(null,'	Santo Domingo Petapa','OAX'),
(null,'Santo Domingo Roayaga','OAX'),
(null,' 	Santo Domingo Tehuantepec','OAX'),
(null,' 	Santo Domingo Teojomulco','OAX'),
(null,' 	Santo Domingo Tepuxtepec','OAX'),
(null,' 	Santo Domingo Tlatayápam','OAX'),
(null,' 	Santo Domingo Tomaltepec','OAX'),
(null,' 	Santo Domingo Tonalá','OAX'),
(null,' 	Santo Domingo Tonaltepec','OAX'),
(null,' 	Santo Domingo Xagacía','OAX'),
(null,' 	Santo Domingo Yanhuitlán','OAX'),
(null,' 	Santo Domingo Yodohino','OAX'),
(null,' 	Santo Domingo Zanatepec','OAX'),
(null,' 	Santo Tomás Jalieza','OAX'),
(null,' 	Santo Tomás Mazaltepec','OAX'),
(null,' 	Santo Tomás Ocotepec','OAX'),
(null,' 	Santo Tomás Tamazulapan','OAX'),
(null,' 	Santos Reyes Nopala','OAX'),
(null,' 	Santos Reyes Pápalo','OAX'),
(null,'	Santos Reyes Tepejillo','OAX'),
(null,' 	Santos Reyes Yucuná','OAX'),
(null,' 	Silacayoápam','OAX'),
(null,' 	Sitio de Xitlapehua','OAX'),
(null,' 	Soledad Etla','OAX'),
(null,' 	Tamazulapam del Espíritu Santo','OAX'),
(null,' 	Tanetze de Zaragoza','OAX'),
(null,' 	Taniche','OAX'),
(null,' 	Tataltepec de Valdés','OAX'),
(null,' 	Teococuilco de Marcos Pérez','OAX'),
(null,' 	Teotitlán de Flores Magón','OAX'),
(null,' 	Teotitlán del Valle','OAX'),
(null,' 	Teotongo','OAX'),
(null,' 	Tepelmeme Villa de Morelos','OAX'),
(null,'	Tezoatlán de Segura y Luna','OAX'),
(null,'	Tlacolula de Matamoros','OAX'),
(null,'	Tlacotepec Plumas','OAX'),
(null,'	Tlalixtac de Cabrera','OAX'),
(null,'	Totontepec Villa de Morelos','OAX'),
(null,'	Trinidad Zaachila','OAX'),
(null,'	Unión Hidalgo','OAX'),
(null,'	Valerio Trujano','OAX'),
(null,'	Villa de Chilapa de Díaz','OAX'),
(null,'	Villa de Etla','OAX'),
(null,'	Villa de Tamazulápam del Progreso','OAX'),
(null,'	Villa de Tututepec de Melchor Ocam','OAX'),
(null,'	Villa de Zaachila','OAX'),
(null,'Villa Díaz Ordaz','OAX'),
(null,'Villa Hidalgo','OAX'),
(null,'Villa Sola de Vega','OAX'),
(null,'Villa Talea de Castro','OAX'),
(null,'Villa Tejúpam de la Unión','OAX'),
(null,'Yaxe ','OAX'),
(null,'Yogana ','OAX'),
(null,'Yutanduchi de Guerrero','OAX'),
(null,'Zapotitlán del Río','OAX'),
(null,'Zapotitlán Lagunas','OAX'),
(null,'Zapotitlán Palmas','OAX'),
(null,'Zimatlán de Alvarez','OAX');

#end region 

# region puebla 217
insert into ciudades values(null,'Acajete','PUE'),(null,'Acateno','PUE'),(null,'Acatlán','PUE'),(null,'Acatzingo','PUE'),(null,'Acteopan','PUE'),(null,'Ahuacatlán','PUE'),
(null,'Ahuatlán','PUE'),(null,'Ahuazotepec','PUE'),(null,'Ahuehuetitla','PUE'),(null,'Ajalpan','PUE'),(null,'Albino Zertuche','PUE'),(null,'Aljojuca','PUE'),
(null,'Altepexi','PUE'),(null,'Amixtlán','PUE'),(null,'Amozoc','PUE'),(null,'Aquixtla','PUE'),(null,'Atempan','PUE'),(null,'Atexcal','PUE'),(null,'Atlequizayan','PUE'),
(null,'Atlixco','PUE'),(null,'Atoyatempan','PUE'),(null,'Atzala','PUE'),(null,'Atzitzihuacán','PUE'),(null,'Atzitzintla','PUE'),(null,'Axutla','PUE'),(null,'Ayotoxco de Guerrero','PUE'),
(null,'Calpan','PUE'),(null,'Caltepec','PUE'),(null,'Camocuautla','PUE'),(null,'Cañada Morelos','PUE'),(null,'Caxhuacan','PUE'),(null,'Chalchicomula de Sesma','PUE'),(null,'Chapulco','PUE'),
(null,'Chiautla','PUE'),(null,'Chiautzingo','PUE'),(null,'Chichiquila','PUE'),(null,'Chiconcuautla','PUE'),(null,'Chietla','PUE'),(null,'Chigmecatitlán','PUE'),(null,'Chignahuapan','PUE'),
(null,'Chignautla','PUE'),(null,'Chila','PUE'),(null,'Chila de la Sal','PUE'),(null,'Chilchotla','PUE'),(null,'Chinantla','PUE'),(null,'Coatepec','PUE'),(null,'Coatzingo','PUE'),
(null,'Cohetzala','PUE'),(null,'Cohuecán','PUE'),(null,'Coronango','PUE'),(null,'Coxcatlán','PUE'),(null,'Coyomeapan','PUE'),(null,'Coyotepec','PUE'),(null,'Cuapiaxtla de Madero','PUE'),
(null,'Cuautempan','PUE'),(null,'Cuautinchán','PUE'),(null,'Cuautlancingo','PUE'),(null,'Cuayuca de Andrade','PUE'),(null,'Cuetzalan del Progreso','PUE'),(null,'Cuyoaco','PUE'),
(null,'Domingo Arenas','PUE'),(null,'Eloxochitlán','PUE'),(null,'Epatlán','PUE'),(null,'Esperanza','PUE'),(null,'Francisco Z. Mena','PUE'),(null,'General Felipe Angeles','PUE'),(null,'Guadalupe','PUE'),
(null,'Guadalupe Victoria','PUE'),(null,'Hermenegildo Galeana','PUE'),(null,'Honey','PUE'),(null,'Huaquechula','PUE'),(null,'Huatlatlauca','PUE'),(null,'Huauchinango','PUE'),(null,'Huehuetla','PUE'),
(null,'Huehuetlán el Chico','PUE'),(null,'Huehuetlán el Grande','PUE'),(null,'Huejotzingo','PUE'),(null,'Hueyapan','PUE'),(null,'Hueytamalco','PUE'),(null,'Hueytlalpan','PUE'),
(null,'Huitzilan de Serdán','PUE'),(null,'Huitziltepec','PUE'),(null,'Ixcamilpa de Guerrero','PUE'),(null,'Ixcaquixtla','PUE'),(null,'Ixtacamaxtitlán','PUE'),(null,'Ixtepec','PUE'),
(null,'Izúcar de Matamoros','PUE'),(null,'Jalpan','PUE'),(null,'Jolalpan','PUE'),(null,'Jonotla','PUE'),(null,'Jopala','PUE'),(null,'Juan C. Bonilla','PUE'),(null,'Juan Galindo','PUE'),
(null,'Juan N. Méndez','PUE'),(null,'La Magdalena Tlatlauquitepec','PUE'),(null,'Lafragua','PUE'),(null,'Libres','PUE'),(null,'Los Reyes de Juárez','PUE'),(null,'Mazapiltepec de Juárez','PUE'),
(null,'Mixtla','PUE'),(null,'Molcaxac','PUE'),(null,'Naupan','PUE'),(null,'Nauzontla','PUE'),(null,'Nealtican','PUE'),(null,'Nicolás Bravo','PUE'),(null,'Nopalucan','PUE'),(null,'Ocotepec','PUE'),
(null,'Ocoyucan','PUE'),(null,'Olintla','PUE'),(null,'Oriental','PUE'),(null,'Pahuatlán','PUE'),(null,'Palmar de Bravo','PUE'),(null,'Petlalcingo','PUE'),(null,'Pantepec','PUE'),
(null,'Piaxtla','PUE'),(null,'Puebla','PUE'),(null,'Quecholac','PUE'),(null,'Quimixtlán','PUE'),(null,'Rafael Lara Grajales','PUE'),(null,'San Andrés Cholula','PUE'),(null,'San Antonio Cañada','PUE'),
(null,'San Diego la Mesa Tochimiltzingo','PUE'),(null,'San Felipe Teotlalcingo','PUE'),(null,'San Felipe Tepatlán','PUE'),(null,'San Gabriel Chilac','PUE'),(null,'San Gregorio Atzompa','PUE'),(null,'San Jerónimo Tecuanipan','PUE'),
(null,'San Jerónimo Xayacatlán','PUE'),(null,'San José Chiapa','PUE'),(null,'San José Miahuatlán','PUE'),(null,'San Juan Atenco','PUE'),(null,'San Juan Atzompa','PUE'),(null,'San Martín Texmelucan','PUE'),
(null,'San Martín Totoltepec','PUE'),(null,'San Matías Tlalancaleca','PUE'),(null,'San Miguel Ixitlán','PUE'),(null,'San Miguel Xoxtla','PUE'),(null,'San Nicolás Buenos Aires','PUE'),
(null,'San Nicolás de los Ranchos','PUE'),(null,'San Pablo Anicano','PUE'),(null,'San Pedro Cholula','PUE'),(null,'San Pedro Yeloixtlahuaca','PUE'),(null,'San Salvador el Seco','PUE'),(null,'San Salvador el Verde','PUE'),
(null,'San Salvador Huixcolotla','PUE'),(null,'San Sebastián Tlacotepec','PUE'),(null,'Santa Catarina Tlaltempan','PUE'),(null,'Santa Inés Ahuatempan','PUE'),(null,'Santa Isabel Cholula','PUE'),(null,'Santiago Miahuatlán','PUE'),
(null,'Santo Tomás Hueyotlipan','PUE'),(null,'Soltepec','PUE'),(null,'Tecali de Herrera','PUE'),(null,'Tecamachalco','PUE'),(null,'Tecomatlán','PUE'),(null,'Tehuacán','PUE'),(null,'Tehuitzingo','PUE'),
(null,'Tenampulco','PUE'),(null,'Teopantlán','PUE'),(null,'Teotlalco','PUE'),(null,'Tepanco de López','PUE'),(null,'Tepango de Rodríguez','PUE'),(null,'Tepatlaxco de Hidalgo','PUE'),
(null,'Tepeaca','PUE'),(null,'Tepemaxalco','PUE'),(null,'Tepeojuma','PUE'),(null,'Tepetzintla','PUE'),(null,'Tepexco','PUE'),(null,'Tepexi de Rodríguez','PUE'),(null,'Tepeyahualco','PUE'),(null,'Tepeyahualco de Cuauhtémoc','PUE'),
(null,'Tetela de Ocampo','PUE'),(null,'Teteles de Avila Castillo','PUE'),(null,'Teziutlán','PUE'),(null,'Tianguismanalco','PUE'),(null,'Tilapa','PUE'),(null,'Tlachichuca','PUE'),(null,'Tlacotepec de Benito Juárez','PUE'),
(null,'Tlacuilotepec','PUE'),(null,'Tlahuapan','PUE'),(null,'Tlaltenango','PUE'),(null,'Tlanepantla','PUE'),(null,'Tlaola','PUE'),(null,'Tlapacoya','PUE'),(null,'Tlapanalá','PUE'),(null,'Tlatlauquitepec','PUE'),(null,'Tlaxco','PUE'),
(null,'Tochimilco','PUE'),(null,'Tochtepec','PUE'),(null,'Totoltepec de Guerrero','PUE'),(null,'Tulcingo','PUE'),(null,'Tuzamapan de Galeana','PUE'),(null,'Tzicatlacoyan','PUE'),(null,'Venustiano Carranza','PUE'),(null,'Vicente Guerrero','PUE'),
(null,'Xayacatlán de Bravo','PUE'),(null,'Xicotepec','PUE'),(null,'Xicotlán','PUE'),(null,'Xiutetelco','PUE'),(null,'Xochiapulco','PUE'),(null,'Xochiltepec','PUE'),(null,'Xochitlán de Vicente Suárez','PUE'),(null,'Xochitlán Todos Santos','PUE'),
(null,'Yaonáhuac','PUE'),(null,'Yehualtepec','PUE'),(null,'Zacapala','PUE'),(null,'Zacapoaxtla','PUE'),(null,'Zacatlán','PUE'),(null,'Zapotitlán','PUE'),(null,'Zapotitlán de Méndez','PUE'),(null,'Zaragoza','PUE'),(null,'Zautla','PUE'),
(null,'Zihuateutla','PUE'),(null,'Zinacatepec','PUE'),(null,'Zongozotla','PUE'),(null,'Zoquiapan','PUE'),(null,'Zoquitlán','PUE');
#end region

#region queretaro 18
insert into ciudades values(null,'Amealco de Bonfil','QUE'),(null,'Arroyo Seco','QUE'),(null,'Cadereyta de Montes','QUE'),(null,'Colón','QUE'),(null,'Corregidora','QUE'),
(null,'El Marqués','QUE'),(null,'Ezequiel Montes','QUE'),(null,'Huimilpan','QUE'),(null,'Jalpan de Serra','QUE'),(null,'Landa de Matamoros','QUE'),(null,'Pedro Escobedo','QUE'),(null,'Peñamiller','QUE'),
(null,'Pinal de Amoles','QUE'),(null,'Querétaro','QUE'),(null,'San Joaquín','QUE'),(null,'San Juan del Río','QUE'),(null,'Tequisquiapan','QUE'),(null,'Tolimán','QUE');
 	
#end region 

#region quintana roo
insert into ciudades values(null,'Benito Juárez','ROO'),(null,'Cozumel','ROO'),(null,'Felipe Carrillo Puerto','ROO'),(null,'Isla Mujeres','ROO'),
(null,'José María Morelos','ROO'),(null,'Lázaro Cárdenas','ROO'),(null,'Othón P. Blanco','ROO'),(null,'Solidaridad','ROO'),(null,'chetumal ','ROO');
 # end region
 
 #region san luis potosi 55
 insert into ciudades values(null,'Ahualulco','SLP'),
	(null,'Alaquines','SLP'),
	(null,'Aquismón','SLP'),
 	(null,'Armadillo de los Infante','SLP'),
 (null,'Axtla de Terrazas','SLP'),
 (null,'Cárdenas','SLP'),
	(null,'Catorce','SLP'),
	(null,'Cedral','SLP'),
	(null,'Cerritos','SLP'),
(null,'Cerro de San Pedro','SLP'),
 	(null,'Charcas','SLP'),
	(null,'Ciudad del Maíz','SLP'),
	(null,'Ciudad Fernández','SLP'),
	(null,'Ciudad Valles','SLP'),
 	(null,'Coxcatlán','SLP'),
 (null,'Ebano','SLP'),
	(null,'El Naranjo','SLP'),
	(null,'Guadalcázar','SLP'),
	(null,'Huehuetlán','SLP'),
 	(null,'Lagunillas','SLP'),
(null,'Matehuala','SLP'),
	(null,'Matlapa','SLP'),
 	(null,'Mexquitic de Carmona','SLP'),
 (null,'Moctezuma','SLP'),
 	(null,'Rayón','SLP'),
 (null,'Rioverde','SLP'),
	(null,'Salinas','SLP'),
 	(null,'San Antonio','SLP'),
 	(null,'San Ciro de Acosta','SLP'),
	(null,'San Luis Potosí','SLP'),
 	(null,'San Martín Chalchicuautla','SLP'),
 	(null,'San Nicolás Tolentino','SLP'),
 	(null,'San Vicente Tancuayalab','SLP'),
 (null,'Santa Catarina','SLP'),
 	(null,'Santa María del Río','SLP'),
 	(null,'Santo Domingo','SLP'),
 	(null,'Soledad de Graciano Sánchez','SLP'),
 (null,'Tamasopo','SLP'),
 	(null,'Tamazunchale','SLP'),
 	(null,'Tampacán','SLP'),
	(null,'Tampamolón Corona','SLP'),
 	(null,'Tamuín','SLP'),
 	(null,'Tancanhuitz','SLP'),
	(null,'Tanlajás','SLP'),
 	(null,'Tanquián de Escobedo','SLP'),
 	(null,'Tierra Nueva','SLP'),
	(null,'Vanegas','SLP'),
	(null,'Venado','SLP'),
 	(null,'Villa de Arista','SLP'),
 (null,'Villa de Arriaga','SLP'),
	(null,'Villa de Guadalupe','SLP'),
 (null,'Villa de la Paz','SLP'),
	(null,'Villa de Ramos','SLP'),
 (null,'Villa de Reyes','SLP'),
 (null,'Villa Hidalgo','SLP'),
	(null,'Villa Juárez','SLP'),
	(null,'Xilitla','SLP'),
 	(null,'Zaragoza','SLP');
  # end region
  
  #region sinaloa 17
  insert into ciudades values(null,'','SIN'),
  (null,'Angostura','SIN'),
  (null,'Badiraguato','SIN'),
  (null,'Choix','SIN'),
  (null,'Concordia','SIN'),
  (null,'Cosalá','SIN'),
  (null,'Culiacán','SIN'),
  (null,'El Fuerte','SIN'),
  (null,'Elota','SIN'),
  (null,'Escuinapa','SIN'),
  (null,'Guasave','SIN'),
  (null,'Mazatlán','SIN'),
  (null,'Mocorito','SIN'),
  (null,'Navolato','SIN'),
  (null,'Rosario','SIN'),
  (null,'Salvador Alvarado','SIN'),
  (null,'San Ignacio','SIN'),
 	(null,'Sinaloa','SIN');
  #end region
  
  # region sonora 69
  insert into ciudades values (null,' Aconchi','SON'),
  (null,'Agua Prieta','SON'),(null,'Alamos','SON'),(null,'Altar','SON'),(null,'Arivechi','SON'),(null,'Arizpe','SON'),(null,'Atil','SON'),
  (null,'Bacadéhuachi','SON'),(null,'Bacanora','SON'),(null,'Bacerac','SON'),(null,'Bacoachi','SON'),(null,'Bácum','SON'),(null,'Banámichi','SON'),
  (null,'Baviácora','SON'),(null,'Bavispe','SON'),(null,'Benito Juárez','SON'),(null,'Benjamín Hill','SON'),(null,'Caborca','SON'),(null,'Cajeme','SON'),
  (null,'Cananea','SON'),(null,'Carbó','SON'),(null,'Cucurpe','SON'),(null,'Cumpas','SON'),(null,'Divisaderos','SON'),(null,'Empalme','SON'),
  (null,'Etchojoa','SON'),(null,'Fronteras','SON'),(null,'General Plutarco Elías Calles','SON'),(null,'Granados','SON'),(null,'Guaymas','SON'),(null,'Hermosillo','SON'),
  (null,'Heroica Nogales','SON'),(null,'Huachinera','SON'),(null,'Huásabas','SON'),(null,'Huatabampo','SON'),(null,'Huépac','SON'),(null,'Imuris','SON'),
  (null,'La Colorada','SON'),(null,'Magdalena','SON'),(null,'Mazatán','SON'),(null,'Moctezuma','SON'),(null,'Naco','SON'),(null,'Nácori Chico','SON'),
  (null,'Nacozari de García','SON'),(null,'Navojoa','SON'),(null,'Onavas','SON'),(null,'Opodepe','SON'),(null,'	Oquitoa','SON'),(null,'Pitiquito','SON'),
  (null,'Puerto Peñasco','SON'),(null,'Quiriego','SON'),(null,'Rayón','SON'),(null,'Rosario','SON'),(null,'Sahuaripa','SON'),(null,'San Felipe de Jesús','SON'),
  (null,'San Ignacio Río Muerto','SON'),(null,'San Javier','SON'),(null,'San Luis Río Colorado','SON'),(null,'San Miguel de Horcasitas','SON'),
  (null,'San Pedro de la Cueva','SON'),(null,'Santa Ana','SON'),(null,'Santa Cruz','SON'),(null,'Sáric','SON'),(null,'Soyopa','SON'),(null,'Suaqui Grande','SON'),
  (null,'Tepache','SON'),(null,'Trincheras','SON'),(null,'Tubutama','SON'),(null,'Ures','SON'),(null,'Villa Hidalgo','SON'),(null,'Villa Pesqueira','SON'),(null,'Yécora','SON');
#end region 

#region tabasco 17
insert into ciudades values(null,'Balancán','TAB'),
	(null,'Cárdenas','TAB'),
	(null,'Centla','TAB'),
 	(null,'Centro','TAB'),
 	(null,'Comalcalco','TAB'),
 	(null,'Cunduacán','TAB'),
 	(null,'Emiliano Zapata','TAB'),
	(null,'Huimanguillo','TAB'),
	(null,'Jalapa','TAB'),
	(null,'Jalpa de Méndez','TAB'),
 	(null,'Jonuta','TAB'),
 	(null,'Macuspana','TAB'),
 	(null,'Nacajuca','TAB'),
	(null,'Paraíso','TAB'),
  (null,' Tacotalpa','TAB'),
 	(null,'Teapa','TAB'),
 	(null,'Tenosique','TAB');

#end region

# region tamaulipas 43
insert into ciudades values(null,'Abasolo','TAM'),
 	(null,'Aldama','TAM'),
	(null,'Altamira','TAM'),
	(null,'Antiguo Morelos','TAM'),
	(null,'Burgos','TAM'),
	(null,'Bustamante','TAM'),
 	(null,'Camargo','TAM'),
 	(null,'Casas','TAM'),
	(null,'Ciudad Madero','TAM'),
 	(null,'Cruillas','TAM'),
 	(null,'El Mante','TAM'),
 	(null,'G?émez','TAM'),
 	(null,'Gómez Farías','TAM'),
 	(null,'González','TAM'),
 	(null,'Guerrero','TAM'),
 	(null,'Gustavo Díaz Ordaz','TAM'),
 	(null,'Hidalgo','TAM'),
 	(null,'Jaumave','TAM'),
 	(null,'Jiménez','TAM'),
 	(null,'Llera','TAM'),
 	(null,'Mainero','TAM'),
 	(null,'Matamoros','TAM'),
 	(null,'Méndez','TAM'),
 	(null,'Mier','TAM'),
 	(null,'Miguel Alemán','TAM'),
 	(null,'Miquihuana','TAM'),
 	(null,'Nuevo Laredo','TAM'),
 	(null,'Nuevo Morelos','TAM'),
 	(null,'Ocampo','TAM'),
 	(null,'Padilla','TAM'),
	(null,'Palmillas','TAM'),
 	(null,'Reynosa','TAM'),
 	(null,'Río Bravo','TAM'),
 	(null,'San Carlos','TAM'),
 	(null,'San Fernando','TAM'),
	(null,'San Nicolás','TAM'),
 	(null,'Soto la Marina','TAM'),
 	(null,'Tampico','TAM'),
 	(null,'Tula','TAM'),
 	(null,'Valle Hermoso','TAM'),
 	(null,'Victoria','TAM'),
	(null,'Villagrán','TAM'),
	(null,'Xicoténcatl','TAM');
# end region

#region tlaxcala 60
insert into ciudades values(null,'Acuamanala de Miguel Hidalgo','TLA'),
      (null,'Altzayanca','TLA'),
	(null,'Amaxac de Guerrero','TLA'),
 	(null,'Apetatitlán de Antonio Carvajal','TLA'),
 	(null,'Apizaco','TLA'),
	(null,'Atlangatepec','TLA'),
 	(null,'Benito Juárez','TLA'),
	(null,'Calpulalpan','TLA'),
 	(null,'Chiautempan','TLA'),
 	(null,'Contla de Juan Cuamatzi','TLA'),
 	(null,'Cuapiaxtla','TLA'),
	(null,'Cuaxomulco','TLA'),
	(null,'El Carmen Tequexquitla','TLA'),
 	(null,'Emiliano Zapata','TLA'),
	(null,'Españita','TLA'),
 	(null,'Huamantla','TLA'),
 	(null,'Hueyotlipan','TLA'),
 	(null,'Ixtacuixtla de Mariano Matamoros','TLA'),
 	(null,'Ixtenco','TLA'),
 	(null,'La Magdalena Tlaltelulco','TLA'),
 	(null,'Lázaro Cárdenas','TLA'),
	(null,'Mazatecochco de José María Morelos','TLA'),
 	(null,'Muñoz de Domingo Arenas','TLA'),
 	(null,'Nanacamilpa de Mariano Arista','TLA'),
 	(null,'Natívitas','TLA'),
 	(null,'Panotla','TLA'),
 	(null,'Papalotla de Xicohténcatl','TLA'),
	(null,'San Damián Texoloc','TLA'),
 	(null,'San Francisco Tetlanohcan','TLA'),
 	(null,'San Jerónimo Zacualpan','TLA'),
 	(null,'San José Teacalco','TLA'),
 	(null,'San Juan Huactzinco','TLA'),
 	(null,'San Lorenzo Axocomanitla','TLA'),
 	(null,'San Lucas Tecopilco','TLA'),
 	(null,'San Pablo del Monte','TLA'),
 	(null,'Sanctórum de Lázaro Cárdenas','TLA'),
 	(null,'Santa Ana Nopalucan','TLA'),
 	(null,'Santa Apolonia Teacalco','TLA'),
 	(null,'Santa Catarina Ayometla','TLA'),
 	(null,'Santa Cruz Quilehtla','TLA'),
	(null,'Santa Cruz Tlaxcala','TLA'),
 	(null,'Santa Isabel Xiloxoxtla','TLA'),
 	(null,'Tenancingo','TLA'),
 	(null,'Teolocholco','TLA'),
 	(null,'Tepetitla de Lardizábal','TLA'),
 	(null,'Tepeyanco','TLA'),
 	(null,'Terrenate','TLA'),
 	(null,'Tetla de la Solidaridad','TLA'),
 	(null,'Tetlatlahuca','TLA'),
 	(null,'Tlaxcala','TLA'),
 	(null,'Tlaxco','TLA'),
 	(null,'Tocatlán','TLA'),
 	(null,'Totolac','TLA'),
	(null,'Tzompantepec','TLA'),
 	(null,'Xaloztoc','TLA'),
 	(null,'Xaltocan','TLA'),
 	(null,'Xicohtzinco','TLA'),
 	(null,'Yauhquemecan','TLA'),
 	(null,'Zacatelco','TLA'),
 	(null,'Zitlaltepec de Trinidad Sánchez Sa','TLA');
#end region 

# region veracruz 203
insert into ciudades values(null,' Acajete','VER'),
	(null,'Acatlán','VER'),
 	(null,'Acayucan','VER'),
 	(null,'Actopan','VER'),
 	(null,'Acula','VER'),
 	(null,'Acultzingo','VER'),
 	(null,'Agua Dulce','VER'),
 	(null,'Alpatláhuac','VER'),
 	(null,'Alto Lucero de Gutiérrez Barrios','VER'),
 	(null,'Altotonga','VER'),
 	(null,'Alvarado','VER'),
 	(null,'Amatitlán','VER'),
 	(null,'Amatlán de los Reyes','VER'),
 	(null,'Angel R. Cabada','VER'),
 	(null,'Apazapan','VER'),
	(null,'Aquila','VER'),
	(null,'Astacinga','VER'),
 	(null,'Atlahuilco','VER'),
 	(null,'Atoyac','VER'),
	(null,'Atzacan','VER'),
 	(null,'Atzalan','VER'),
 	(null,'Ayahualulco','VER'),
 	(null,'Banderilla','VER'),
 	(null,'Benito Juárez','VER'),
 	(null,'Boca del Río','VER'),
	(null,'Calcahualco','VER'),
 	(null,'Camarón de Tejeda','VER'),
 	(null,'Camerino Z. Mendoza','VER'),
 	(null,'Carlos A. Carrillo','VER'),
 	(null,'Carrillo Puerto','VER'),
 	(null,'Castillo de Teayo','VER'),
 	(null,'Catemaco','VER'),
 	(null,'Cazones','VER'),
 	(null,'Cerro Azul','VER'),
 	(null,'Chacaltianguis','VER'),
 	(null,'Chalma','VER'),
 	(null,'Chiconamel','VER'),
 	(null,'Chiconquiaco','VER'),
 	(null,'Chicontepec','VER'),
 	(null,'Chinameca','VER'),
 	(null,'Chinampa de Gorostiza','VER'),
 	(null,'Chocamán','VER'),
 	(null,'Chontla','VER'),
 	(null,'Chumatlán','VER'),
 	(null,'Citlaltépetl','VER'),
 	(null,'Coacoatzintla','VER'),
 	(null,'Coahuitlán','VER'),
 	(null,'Coatepec','VER'),
 	(null,'Coatzacoalcos','VER'),
 	(null,'Coetzala','VER'),
 	(null,'Colipa','VER'),
 	(null,'Comapa','VER'),
 	(null,'Córdoba','VER'),
 	(null,'Cosamaloapan de Carpio','VER'),
 	(null,'Cosautlán de Carvajal','VER'),
	(null,'Coscomatepec','VER'),
	(null,'Cosoleacaque','VER'),
 	(null,'Cotaxtla','VER'),
 	(null,'Coxquihui','VER'),
 	(null,'Coyutla','VER'),
 	(null,'Cuichapa','VER'),
 	(null,'Cuitláhuac','VER'),
 	(null,'El Higo','VER'),
 	(null,'Emiliano Zapata','VER'),
 	(null,'Espinal','VER'),
 	(null,'Filomeno Mata','VER'),
 	(null,'Fortín','VER'),
 	(null,'Gutiérrez Zamora','VER'),
 	(null,'Hidalgotitlán','VER'),
 	(null,'Huatusco','VER'),
 	(null,'Huayacocotla','VER'),
 	(null,'Hueyapan de Ocampo','VER'),
 	(null,'Huiloapan','VER'),
	(null,'Ignacio de la Llave','VER'),
 	(null,'Ilamatlán','VER'),
 	(null,'Isla','VER'),
 	(null,'Ixcatepec','VER'),
 	(null,'Ixhuacán de los Reyes','VER'),
 	(null,'Ixhuatlán de Madero','VER'),
 	(null,'Ixhuatlán del Café','VER'),
 	(null,'Ixhuatlán del Sureste','VER'),
 	(null,'Ixhuatlancillo','VER'),
 	(null,'Ixmatlahuacan','VER'),
 	(null,'Ixtaczoquitlán','VER'),
 	(null,'Jalacingo','VER'),
 	(null,'Jalcomulco','VER'),
 	(null,'Jáltipan','VER'),
 	(null,'Jamapa','VER'),
	(null,'Jesús Carranza','VER'),
	(null,'Jilotepec','VER'),
	(null,'José Azueta','VER'),
 	(null,'Juan Rodríguez Clara','VER'),
 	(null,'Juchique de Ferrer','VER'),
	(null,'La Antigua','VER'),
 	(null,'La Perla','VER'),
 	(null,'Landero y Coss','VER'),
	(null,'Las Choapas','VER'),
 	(null,'Las Minas','VER'),
 	(null,'Las Vigas de Ramírez','VER'),
 	(null,'Lerdo de Tejada','VER'),
 	(null,'Los Reyes','VER'),
 	(null,'Magdalena','VER'),
 	(null,'Maltrata','VER'),
 	(null,'Manlio Fabio Altamirano','VER'),
 	(null,'Mariano Escobedo','VER'),
	(null,'Martínez de la Torre','VER'),
 	(null,'Mecatlán','VER'),
 	(null,'Mecayapan','VER'),
 	(null,'Medellín','VER'),
	(null,'Miahuatlán','VER'),
 	(null,'Minatitlán','VER'),
 	(null,'Misantla','VER'),
 	(null,'Mixtla de Altamirano','VER'),
 	(null,'Moloacán','VER'),
 	(null,'Nanchital de Lázaro Cárdenas del R','VER'),
 	(null,'Naolinco','VER'),
 	(null,'Naranjal','VER'),
 	(null,'Naranjos Amatlán','VER'),
 	(null,'Nautla','VER'),
 	(null,'Nogales','VER'),
 	(null,'Oluta','VER'),
	(null,'Omealca','VER'),
	(null,'Orizaba','VER'),
 	(null,'Otatitlán','VER'),
 	(null,'Oteapan','VER'),
 	(null,'Ozuluama de Mascareñas','VER'),
 	(null,'Pajapan','VER'),
 	(null,'Pánuco','VER'),
 	(null,'Papantla','VER'),
 	(null,'Paso de Ovejas','VER'),
 	(null,'Paso del Macho','VER'),
 	(null,'Perote','VER'),
 	(null,'Platón Sánchez','VER'),
 	(null,'Playa Vicente','VER'),
 	(null,'Poza Rica de Hidalgo','VER'),
 	(null,'Pueblo Viejo','VER'),
	(null,'Puente Nacional','VER'),
 	(null,'Rafael Delgado','VER'),
 	(null,'Rafael Lucio','VER'),
 	(null,'Río Blanco','VER'),
 	(null,'Saltabarranca','VER'),
 	(null,'San Andrés Tenejapan','VER'),
 	(null,'San Andrés Tuxtla','VER'),
 	(null,'San Juan Evangelista','VER'),
 	(null,'San Rafael','VER'),
 	(null,'Santiago Sochiapan','VER'),
 	(null,'Santiago Tuxtla','VER'),
 	(null,'Sayula de Alemán','VER'),
 	(null,'Sochiapa','VER'),
	(null,'Soconusco','VER'),
	(null,'Soledad Atzompa','VER'),
 	(null,'Soledad de Doblado','VER'),
 	(null,'Soteapan','VER'),
 	(null,'Tamalín','VER'),
 	(null,'Tamiahua','VER'),
	(null,'Tampico Alto','VER'),
	(null,'Tancoco','VER'),
 	(null,'Tantima','VER'),
	(null,'Tantoyuca','VER'),
 	(null,'Tatahuicapan de Juárez','VER'),
 	(null,'Tatatila','VER'),
	(null,'Tecolutla','VER'),
 	(null,'Tehuipango','VER'),
 	(null,'Temapache','VER'),
 	(null,'Tempoal','VER'),
 	(null,'Tenampa','VER'),
 	(null,'Tenochtitlán','VER'),
 	(null,'Teocelo','VER'),
 	(null,'Tepatlaxco','VER'),
 	(null,'Tepetlán','VER'),
 	(null,'Tepetzintla','VER'),
	(null,'Tequila','VER'),
 	(null,'Texcatepec','VER'),
 	(null,'Texhuacán','VER'),
 	(null,'Texistepec','VER'),
 	(null,'Tezonapa','VER'),
 	(null,'Tierra Blanca','VER'),
 	(null,'Tihuatlán','VER'),
 	(null,'Tlachichilco','VER'),
 	(null,'Tlacojalpan','VER'),
 	(null,'Tlacolulan','VER'),
 	(null,'Tlacotalpan','VER'),
 	(null,'Tlacotepec de Mejía','VER'),
 	(null,'Tlalixcoyan','VER'),
 	(null,'Tlalnelhuayocan','VER'),
 	(null,'Tlaltetela','VER'),
 	(null,'Tlapacoyan','VER'),
 	(null,'Tlaquilpa','VER'),
	(null,'Tlilapan','VER'),
 	(null,'Tomatlán','VER'),
 	(null,'Tonayán','VER'),
 	(null,'Totutla','VER'),
 	(null,'Tres Valles','VER'),
 	(null,'Túxpam','VER'),
	(null,'Tuxtilla','VER'),
 	(null,'Ursulo Galván','VER'),
 	(null,'Uxpanapa','VER'),
	(null,'Vega de Alatorre','VER'),
 	(null,'Veracruz','VER'),
 	(null,'Villa Aldama','VER'),
 	(null,'Xalapa','VER'),
 	(null,'Xico','VER'),
 	(null,'Xoxocotla','VER'),
	(null,'Yanga','VER'),
	(null,'Yecuatla','VER'),
 	(null,'Zacualpan','VER'),
 	(null,'Zaragoza','VER'),
 	(null,'Zentla','VER'),
 	(null,'Zongolica','VER'),
	(null,'Zontecomatlán de López y Fuentes','VER'),
	(null,'Zozocolco de Hidalgo','VER');

#end region

# region yucatan  106
 insert into ciudades values(null,'Abalá','YUC'),
 	(null,'Acanceh','YUC'),
 	(null,'Akil','YUC'),
 	(null,'Baca','YUC'),
 	(null,'Bokobá','YUC'),
 	(null,'Buctzotz','YUC'),
	(null,'Cacalchén','YUC'),
 	(null,'Calotmul','YUC'),
	(null,'Cansahcab','YUC'),
 	(null,'Cantamayec','YUC'),
 	(null,'Celestún','YUC'),
 	(null,'Cenotillo','YUC'),
 	(null,'Chacsinkín','YUC'),
 	(null,'Chankom','YUC'),
 	(null,'Chapab','YUC'),
 	(null,'Chemax','YUC'),
 	(null,'Chichimilá','YUC'),
 	(null,'Chicxulub Pueblo','YUC'),
 	(null,'Chikindzonot','YUC'),
 	(null,'Chocholá','YUC'),
 	(null,'Chumayel','YUC'),
 	(null,'Conkal','YUC'),
	(null,'Cuncunul','YUC'),
 	(null,'Cuzamá','YUC'),
 	(null,'Dzán','YUC'),
	(null,'Dzemul','YUC'),
 	(null,'Dzidzantún','YUC'),
 	(null,'Dzilam de Bravo','YUC'),
 	(null,'Dzilam González','YUC'),
 	(null,'Dzitás','YUC'),
 	(null,'Dzoncauich','YUC'),
 	(null,'Espita','YUC'),
 	(null,'Halachó','YUC'),
 	(null,'Hocabá','YUC'),
 	(null,'Hoctún','YUC'),
 	(null,'Homún','YUC'),
 	(null,'Huhí','YUC'),
 	(null,'Hunucmá','YUC'),
 	(null,'Ixil','YUC'),
 	(null,'Izamal','YUC'),
 	(null,'Kanasín','YUC'),
 	(null,'Kantunil','YUC'),
 	(null,'Kaua','YUC'),
 	(null,'Kinchil','YUC'),
 	(null,'Kopomá','YUC'),
 	(null,'Mama','YUC'),
 	(null,'Maní','YUC'),
 	(null,'Maxcanú','YUC'),
 	(null,'Mayapán','YUC'),
 	(null,'Mérida','YUC'),
 	(null,'Mocochá','YUC'),
 	(null,'Motul','YUC'),
 	(null,'Muna','YUC'),
 	(null,'Muxupip','YUC'),
	(null,'Opichén','YUC'),
 	(null,'Oxkutzcab','YUC'),
 	(null,'Panabá','YUC'),
 	(null,'Peto','YUC'),
 	(null,'Progreso','YUC'),
 	(null,'Quintana Roo','YUC'),
 	(null,'Río Lagartos','YUC'),
	(null,'Sacalum','YUC'),
 	(null,'Samahil','YUC'),
 	(null,'San Felipe','YUC'),
 	(null,'Sanahcat','YUC'),
 	(null,'Santa Elena','YUC'),
	(null,'Seyé','YUC'),
 	(null,'Sinanché','YUC'),
 	(null,'Sotuta','YUC'),
	(null,'Sucilá','YUC'),
	(null,'Sudzal','YUC'),
	(null,'Suma','YUC'),
	(null,'Tahdziú','YUC'),
	(null,'Tahmek','YUC'),
	(null,'Teabo','YUC'),
	(null,'Tecoh','YUC'),
	(null,'Tekal de Venegas','YUC'),
	(null,'Tekantó','YUC'),
	(null,'Tekax','YUC'),
	(null,'Tekit','YUC'),
	(null,'Tekom','YUC'),
	(null,'Telchac Pueblo','YUC'),
	(null,'Telchac Puerto','YUC'),
	(null,'Temax','YUC'),
	(null,'Temozón','YUC'),
	(null,'Tepakán','YUC'),
	(null,'Tetiz','YUC'),
	(null,'Teya','YUC'),
	(null,'Ticul','YUC'),
	(null,'Timucuy','YUC'),
	(null,'Tinum','YUC'),
 	(null,'Tixcacalcupul','YUC'),
	(null,'Tixkokob','YUC'),
	(null,'Tixmehuac','YUC'),
	(null,'Tixpéhual','YUC'),
	(null,'Tizimín','YUC'),
	(null,'Tunkás','YUC'),
	(null,'Tzucacab','YUC'),
	(null,'Uayma','YUC'),
	(null,'Ucú','YUC'),
	(null,'Umán','YUC'),
	(null,'Valladolid','YUC'),
	(null,'Xocchel','YUC'),
	(null,'Yaxcabá','YUC'),
	(null,'Yaxkukul','YUC'),
	(null,'Yobaín','YUC');

#end region 

#region zacatecas 56
insert into ciudades values(null,'Apozol','ZAC'),
	(null,'Apulco','ZAC'),
	(null,'Atolinga','ZAC'),
	(null,'Benito Juárez','ZAC'),
	(null,'Calera','ZAC'),
	(null,'Cañitas de Felipe Pescador','ZAC'),
 	(null,'Chalchihuites','ZAC'),
	(null,'Concepción del Oro','ZAC'),
	(null,'Cuauhtémoc','ZAC'),
	(null,'El Plateado de Joaquín Amaro','ZAC'),
	(null,'El Salvador','ZAC'),
	(null,'Fresnillo','ZAC'),
	(null,'Genaro Codina','ZAC'),
	(null,'General Enrique Estrada','ZAC'),
	(null,'General Francisco R. Murguía','ZAC'),
	(null,'General Pánfilo Natera','ZAC'),
	(null,'Guadalupe','ZAC'),
	(null,'Huanusco','ZAC'),
	(null,'Jalpa','ZAC'),
	(null,'Jerez','ZAC'),
	(null,'Jiménez del Teul','ZAC'),
	(null,'Juan Aldama','ZAC'),
	(null,'Juchipila','ZAC'),
	(null,'Loreto','ZAC'),
	(null,'Luis Moya','ZAC'),
	(null,'Mazapil','ZAC'),
	(null,'Melchor Ocampo','ZAC'),
	(null,'Mezquital del Oro','ZAC'),
	(null,'Miguel Auza','ZAC'),
	(null,'Momax','ZAC'),
	(null,'Monte Escobedo','ZAC'),
	(null,'Morelos','ZAC'),
	(null,'Moyahua de Estrada','ZAC'),
 	(null,'Nochistlán de Mejía','ZAC'),
	(null,'Noria de ?ngeles','ZAC'),
	(null,'Ojocaliente','ZAC'),
	(null,'Pánuco','ZAC'),
	(null,'Pinos','ZAC'),
	(null,'Río Grande','ZAC'),
	(null,'Sain Alto','ZAC'),
	(null,'Santa María de la Paz','ZAC'),
	(null,'Sombrerete','ZAC'),
	(null,'Susticacán','ZAC'),
	(null,'Tabasco','ZAC'),
	(null,'Tepechitlán','ZAC'),
	(null,'Tepetongo','ZAC'),
	(null,'Teul de González Ortega','ZAC'),
	(null,'Tlaltenango de Sánchez Román','ZAC'),
	(null,'Trancoso','ZAC'),
	(null,'Trinidad García de la Cadena','ZAC'),
	(null,'Valparaíso','ZAC'),
	(null,'Vetagrande','ZAC'),
	(null,'Villa deCos','ZAC'),
	(null,'Villa García','ZAC'),
	(null,'Villa González Ortega','ZAC'),
	(null,'Villa Hidalgo','ZAC'),
	(null,'Villanueva','ZAC'),
 	(null,'Zacatecas','ZAC');

#end region 



create table maestros(idma int auto_increment primary key,numerodecontrol varchar(50),nombre varchar(50),apellidopaterno varchar(50)
,apellidomaterno varchar(50),direccion varchar(50),ciudad varchar(50),estado varchar(50),numerocedula int,
titulo varchar(50)
,fechanacimiento varchar(50));

create table estudios(ides int auto_increment primary key,fkidma int ,titulo varchar(50),
documento varchar(100),foreign key(fkidma) references maestros(idma));

/*hacer una vista y meterla a visual*/

create view V_vista as 
select nombre,estudios.titulo,documento from maestros,estudios ;

create table Materias(idmateria int primary key auto_increment,nombremateria varchar(100),horasteoria int, horaspractica int,
carrera varchar(100), semestre varchar(100)
);

create table calificaciones(idnota int primary key auto_increment, fkNumControl int , fkidma int,fkidmateria int,creditos int,
foreign key(fkNumControl)references alumno(NumControl),foreign key(fkidma)references maestros(idma),
foreign key(fkidmateria)references Materias(idmateria));

create view V_Ver as
select alumno.nombre, nombremateria,carrera,semestre ,maestros.nombre as "profesor" ,creditos from alumno,
Materias, maestros,calificaciones where NumControl = fkNumControl and idma = fkidma and idmateria = fkidmateria;

select * from V_ver;

create table ligas(idliga int primary key auto_increment, nombreliga varchar (100), materias varchar(100)); /*crear en visual*/

create view V_ligas as
select  nombreliga,nombremateria  from ligas,Materias; 

select * from  V_ligas;

create table escuela(idescuela int primary key auto_increment, nombreescuela varchar(100), RFC varchar(100),domicilioescuela varchar(100),
numerotelefono int, correo varchar(100), paginaWEB varchar(100), directora varchar(100),logo varchar(100));
select * from escuela;
drop table escuela;